import { ExpenseCategory } from '../types';

export const CONDITIONAL_TAX_NOTICE = 
  'Dedução condicionada à relação com a atividade profissional, documentação e demais requisitos fiscais. Consulte seu contador.';

export interface OperationalGroupDef {
  code: string;
  name: string; // Nome oficial descritivo completo
  shortName: string; // Nome curto
  description: string; // O que compõe esse grupo operacional
  isVariableCpv: boolean;
  badgeColor: string;
}

export const OPERATIONAL_EXPENSE_GROUPS: Record<string, OperationalGroupDef> = {
  '01': {
    code: '01',
    name: '01 - Salários e Equipe (Pessoal & Folha)',
    shortName: 'Salários e Equipe',
    description: 'Folha de pagamento da secretária/ASB, 13º salário, férias, FGTS, encargos e pró-labore dos sócios.',
    isVariableCpv: false,
    badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  },
  '02': {
    code: '02',
    name: '02 - Imóveis e Ocupação (Aluguel & Condomínio)',
    shortName: 'Imóveis e Ocupação',
    description: 'Aluguel do consultório/sala comercial, condomínio edilício, IPTU, monitoramento, alarme e conservação predial.',
    isVariableCpv: false,
    badgeColor: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  '03': {
    code: '03',
    name: '03 - Utilidades e Consumo (Energia, Água & Internet)',
    shortName: 'Utilidades e Consumo',
    description: 'Energia elétrica (alta voltagem compressores/autoclave), água e esgoto, internet fibra óptica e telefonia fixa/móvel.',
    isVariableCpv: false,
    badgeColor: 'bg-sky-50 text-sky-700 border-sky-200',
  },
  '04': {
    code: '04',
    name: '04 - Materiais Odontológicos e Insumos Clínicos',
    shortName: 'Materiais Odontológicos (CPV)',
    description: 'Custos variáveis diretos de procedimentos: resinas, anestésicos, agulhas, fios de sutura, moldagens e implantes.',
    isVariableCpv: true,
    badgeColor: 'bg-teal-50 text-teal-700 border-teal-200',
  },
  '05': {
    code: '05',
    name: '05 - Biossegurança e Esterilização (EPIs & Descarte)',
    shortName: 'Biossegurança e Esterilização',
    description: 'EPIs odontológicos, luvas de procedimento/cirúrgicas, máscaras, detergente enzimático, envelopes e coleta de resíduos infectantes.',
    isVariableCpv: false,
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  '06': {
    code: '06',
    name: '06 - Laboratório de Prótese e Apoio Clínico (TPD)',
    shortName: 'Laboratório de Prótese (CPV)',
    description: 'Custos variáveis diretos de protéticos e terceiros: coroas em zircônia/metalocerâmica, placas de bruxismo e exames radiológicos.',
    isVariableCpv: true,
    badgeColor: 'bg-purple-50 text-purple-700 border-purple-200',
  },
  '07': {
    code: '07',
    name: '07 - Manutenção e Conservação de Equipamentos',
    shortName: 'Manutenção de Equipamentos',
    description: 'Manutenção técnica preventiva e corretiva de cadeiras odontológicas, compressores, autoclaves, peças de mão e raio-X.',
    isVariableCpv: false,
    badgeColor: 'bg-orange-50 text-orange-700 border-orange-200',
  },
  '08': {
    code: '08',
    name: '08 - Gestão Administrativa e Contábil',
    shortName: 'Gestão Administrativa & Contábil',
    description: 'Honorários de contabilidade odontológica, assessoria jurídica, cartório, correios e material de escritório.',
    isVariableCpv: false,
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  '09': {
    code: '09',
    name: '09 - Tecnologia e Softwares Odontológicos',
    shortName: 'Tecnologia e Softwares',
    description: 'Prontuário eletrônico em nuvem, software financeiro, backup criptografado, emissor fiscal e WhatsApp Business.',
    isVariableCpv: false,
    badgeColor: 'bg-cyan-50 text-cyan-700 border-cyan-200',
  },
  '10': {
    code: '10',
    name: '10 - Marketing e Captação de Pacientes',
    shortName: 'Marketing e Captação',
    description: 'Investimento em tráfego pago (Google Ads, Meta Ads), agência de marketing odontológico, site e fotos profissionais.',
    isVariableCpv: false,
    badgeColor: 'bg-pink-50 text-pink-700 border-pink-200',
  },
  '11': {
    code: '11',
    name: '11 - Desenvolvimento Profissional e CRO',
    shortName: 'Profissional e CRO',
    description: 'Anuidade obrigatória do CRO/CFO, sindicatos, associações científicas (ABO/APCD), congressos (CIOSP) e cursos.',
    isVariableCpv: false,
    badgeColor: 'bg-violet-50 text-violet-700 border-violet-200',
  },
  '12': {
    code: '12',
    name: '12 - Despesas Bancárias e Financeiras',
    shortName: 'Financeiro e Maquininhas',
    description: 'Taxas de antecipação e MDR de maquininhas de cartão de crédito/débito, tarifas de conta corrente PJ/PF e juros.',
    isVariableCpv: false,
    badgeColor: 'bg-slate-50 text-slate-700 border-slate-200',
  },
  '13': {
    code: '13',
    name: '13 - Impostos e Obrigações Fiscais (DAS, ISS, Carnê-Leão)',
    shortName: 'Impostos e Obrigações',
    description: 'Guias DAS do Simples Nacional da clínica, ISS municipal, IRPF Carnê-Leão pago, INSS GPS do profissional e taxas sanitárias.',
    isVariableCpv: false,
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  '14': {
    code: '14',
    name: '14 - Investimentos e Equipamentos (Ativo Imobilizado)',
    shortName: 'Investimentos e Equipamentos',
    description: 'Aquisição de bens duráveis e modernização: cadeiras odontológicas, scanner intraoral 3D, autoclave nova e reformas estruturais.',
    isVariableCpv: false,
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  '15': {
    code: '15',
    name: '15 - Transporte e Logística Operacional',
    shortName: 'Transporte e Logística',
    description: 'Combustível, estacionamento, pedágio e transporte para compras de insumos, cartórios ou visitas a laboratórios.',
    isVariableCpv: false,
    badgeColor: 'bg-yellow-50 text-yellow-700 border-yellow-200',
  },
  '16': {
    code: '16',
    name: '16 - Despesas Pessoais / Não Operacionais',
    shortName: 'Despesas Pessoais',
    description: 'Retiradas particulares de lucros isentos dos sócios e despesas pessoais não relacionadas ao funcionamento da clínica.',
    isVariableCpv: false,
    badgeColor: 'bg-stone-50 text-stone-700 border-stone-200',
  },
};

export function getOperationalGroup(code: string): OperationalGroupDef {
  return OPERATIONAL_EXPENSE_GROUPS[code] || {
    code,
    name: `${code} - Despesas Grupo ${code}`,
    shortName: `Grupo ${code}`,
    description: 'Despesas e lançamentos operacionais da clínica.',
    isVariableCpv: false,
    badgeColor: 'bg-slate-50 text-slate-700 border-slate-200',
  };
}

export function getOperationalGroupName(code: string): string {
  const g = OPERATIONAL_EXPENSE_GROUPS[code];
  return g ? g.name : `Grupo ${code}`;
}

const RAW_CHART_OF_ACCOUNTS: ExpenseCategory[] = [
  // 01 - PESSOAL
  {
    id: 'cat_01_01',
    code: '01.01',
    groupCode: '01',
    groupName: '01 - PESSOAL',
    name: 'Salários',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_01_02',
    code: '01.02',
    groupCode: '01',
    groupName: '01 - PESSOAL',
    name: 'Férias',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_01_03',
    code: '01.03',
    groupCode: '01',
    groupName: '01 - PESSOAL',
    name: '13º Salário',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_01_04',
    code: '01.04',
    groupCode: '01',
    groupName: '01 - PESSOAL',
    name: 'FGTS',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_01_05',
    code: '01.05',
    groupCode: '01',
    groupName: '01 - PESSOAL',
    name: 'Encargos previdenciários de empregados',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_01_06',
    code: '01.06',
    groupCode: '01',
    groupName: '01 - PESSOAL',
    name: 'Benefícios (VT, VR, Saúde)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_01_07',
    code: '01.07',
    groupCode: '01',
    groupName: '01 - PESSOAL',
    name: 'Pró-labore',
    dedutivelLivroCaixaPf: 'NAO', // Pró-labore é remuneração societária PJ, não é dedutível no Livro Caixa da PF
    impactaFatorRPj: true, // Crucial para o cálculo do Fator R no Simples Nacional
    despesaOperacionalPj: true,
    active: true,
    noticeText: 'Pró-labore compõe a folha de salários para Fator R da PJ, mas não é despesa dedutível no Livro Caixa PF.',
  },
  {
    id: 'cat_01_08',
    code: '01.08',
    groupCode: '01',
    groupName: '01 - PESSOAL',
    name: 'Serviços de terceiros',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },

  // 02 - OCUPAÇÃO
  {
    id: 'cat_02_01',
    code: '02.01',
    groupCode: '02',
    groupName: '02 - OCUPAÇÃO',
    name: 'Aluguel do consultório',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_02_02',
    code: '02.02',
    groupCode: '02',
    groupName: '02 - OCUPAÇÃO',
    name: 'Condomínio',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_02_03',
    code: '02.03',
    groupCode: '02',
    groupName: '02 - OCUPAÇÃO',
    name: 'IPTU e taxas do imóvel',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_02_04',
    code: '02.04',
    groupCode: '02',
    groupName: '02 - OCUPAÇÃO',
    name: 'Segurança e alarme',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_02_05',
    code: '02.05',
    groupCode: '02',
    groupName: '02 - OCUPAÇÃO',
    name: 'Limpeza e conservação',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },

  // 03 - UTILIDADES
  {
    id: 'cat_03_01',
    code: '03.01',
    groupCode: '03',
    groupName: '03 - UTILIDADES',
    name: 'Energia elétrica',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_03_02',
    code: '03.02',
    groupCode: '03',
    groupName: '03 - UTILIDADES',
    name: 'Água e esgoto',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_03_03',
    code: '03.03',
    groupCode: '03',
    groupName: '03 - UTILIDADES',
    name: 'Telefone profissional',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_03_04',
    code: '03.04',
    groupCode: '03',
    groupName: '03 - UTILIDADES',
    name: 'Internet',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },

  // 04 - MATERIAIS ODONTOLÓGICOS
  {
    id: 'cat_04_01',
    code: '04.01',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Materiais restauradores (resinas, adesivos)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_04_02',
    code: '04.02',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Anestésicos e agulhas',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_04_03',
    code: '04.03',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Materiais cirúrgicos e fios de sutura',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_04_04',
    code: '04.04',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Ortodontia (braquetes, fios, elásticos)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_04_05',
    code: '04.05',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Endodontia (limas, cones, cimentos)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_04_06',
    code: '04.06',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Implantodontia (implantes, cicatrizadores)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_04_07',
    code: '04.07',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Materiais de moldagem (alginato, silicone)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_04_08',
    code: '04.08',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Materiais descartáveis e sugadores',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_04_09',
    code: '04.09',
    groupCode: '04',
    groupName: '04 - MATERIAIS ODONTOLÓGICOS',
    name: 'Outros materiais clínicos',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },

  // 05 - BIOSSEGURANÇA
  {
    id: 'cat_05_01',
    code: '05.01',
    groupCode: '05',
    groupName: '05 - BIOSSEGURANÇA',
    name: 'Luvas de procedimento e cirúrgicas',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_05_02',
    code: '05.02',
    groupCode: '05',
    groupName: '05 - BIOSSEGURANÇA',
    name: 'Máscaras descartáveis e N95',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_05_03',
    code: '05.03',
    groupCode: '05',
    groupName: '05 - BIOSSEGURANÇA',
    name: 'EPIs (gorros, propés, aventais)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_05_04',
    code: '05.04',
    groupCode: '05',
    groupName: '05 - BIOSSEGURANÇA',
    name: 'Esterilização (envelopes, indicadores, detergente enzimático)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_05_05',
    code: '05.05',
    groupCode: '05',
    groupName: '05 - BIOSSEGURANÇA',
    name: 'Produtos de limpeza hospitalar',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_05_06',
    code: '05.06',
    groupCode: '05',
    groupName: '05 - BIOSSEGURANÇA',
    name: 'Coleta e descarte de resíduos infectantes',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },

  // 06 - LABORATÓRIO E SERVIÇOS CLÍNICOS
  {
    id: 'cat_06_01',
    code: '06.01',
    groupCode: '06',
    groupName: '06 - LABORATÓRIO E SERVIÇOS CLÍNICOS',
    name: 'Laboratório de prótese (TPD)',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_06_02',
    code: '06.02',
    groupCode: '06',
    groupName: '06 - LABORATÓRIO E SERVIÇOS CLÍNICOS',
    name: 'Radiologia e tomografia',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_06_03',
    code: '06.03',
    groupCode: '06',
    groupName: '06 - LABORATÓRIO E SERVIÇOS CLÍNICOS',
    name: 'Serviços laboratoriais de biópsia/análise',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_06_04',
    code: '06.04',
    groupCode: '06',
    groupName: '06 - LABORATÓRIO E SERVIÇOS CLÍNICOS',
    name: 'Profissionais parceiros terceirizados',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },

  // 07 - MANUTENÇÃO
  {
    id: 'cat_07_01',
    code: '07.01',
    groupCode: '07',
    groupName: '07 - MANUTENÇÃO',
    name: 'Manutenção de cadeira odontológica',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_07_02',
    code: '07.02',
    groupCode: '07',
    groupName: '07 - MANUTENÇÃO',
    name: 'Manutenção de autoclave',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_07_03',
    code: '07.03',
    groupCode: '07',
    groupName: '07 - MANUTENÇÃO',
    name: 'Manutenção de compressor',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_07_04',
    code: '07.04',
    groupCode: '07',
    groupName: '07 - MANUTENÇÃO',
    name: 'Manutenção de Raio-X',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_07_05',
    code: '07.05',
    groupCode: '07',
    groupName: '07 - MANUTENÇÃO',
    name: 'Equipamentos clínicos (peças de mão, ultrassom)',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_07_06',
    code: '07.06',
    groupCode: '07',
    groupName: '07 - MANUTENÇÃO',
    name: 'Manutenção predial e encanamento',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },

  // 08 - ADMINISTRATIVO
  {
    id: 'cat_08_01',
    code: '08.01',
    groupCode: '08',
    groupName: '08 - ADMINISTRATIVO',
    name: 'Papelaria e receituários',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_08_02',
    code: '08.02',
    groupCode: '08',
    groupName: '08 - ADMINISTRATIVO',
    name: 'Material de escritório consumível',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_08_03',
    code: '08.03',
    groupCode: '08',
    groupName: '08 - ADMINISTRATIVO',
    name: 'Correios e malotes',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_08_04',
    code: '08.04',
    groupCode: '08',
    groupName: '08 - ADMINISTRATIVO',
    name: 'Contabilidade e assessoria fiscal',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_08_05',
    code: '08.05',
    groupCode: '08',
    groupName: '08 - ADMINISTRATIVO',
    name: 'Assessoria jurídica profissional',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },

  // 09 - TECNOLOGIA
  {
    id: 'cat_09_01',
    code: '09.01',
    groupCode: '09',
    groupName: '09 - TECNOLOGIA',
    name: 'Software odontológico e prontuário',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_09_02',
    code: '09.02',
    groupCode: '09',
    groupName: '09 - TECNOLOGIA',
    name: 'Software financeiro e cobrança',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_09_03',
    code: '09.03',
    groupCode: '09',
    groupName: '09 - TECNOLOGIA',
    name: 'Armazenamento em nuvem e backup seguro',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_09_04',
    code: '09.04',
    groupCode: '09',
    groupName: '09 - TECNOLOGIA',
    name: 'Telefonia digital e WhatsApp Business',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_09_05',
    code: '09.05',
    groupCode: '09',
    groupName: '09 - TECNOLOGIA',
    name: 'Sistemas e assinaturas digitais',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },

  // 10 - MARKETING
  {
    id: 'cat_10_01',
    code: '10.01',
    groupCode: '10',
    groupName: '10 - MARKETING',
    name: 'Tráfego pago (Google Ads, Meta Ads)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_10_02',
    code: '10.02',
    groupCode: '10',
    groupName: '10 - MARKETING',
    name: 'Agência de marketing',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_10_03',
    code: '10.03',
    groupCode: '10',
    groupName: '10 - MARKETING',
    name: 'Site da clínica e domínio',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_10_04',
    code: '10.04',
    groupCode: '10',
    groupName: '10 - MARKETING',
    name: 'Design e identidade visual',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_10_05',
    code: '10.05',
    groupCode: '10',
    groupName: '10 - MARKETING',
    name: 'Impressos de divulgação e cartões',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_10_06',
    code: '10.06',
    groupCode: '10',
    groupName: '10 - MARKETING',
    name: 'Publicidade e propaganda profissional',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },

  // 11 - PROFISSIONAL
  {
    id: 'cat_11_01',
    code: '11.01',
    groupCode: '11',
    groupName: '11 - PROFISSIONAL',
    name: 'Anuidade do CRO',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_11_02',
    code: '11.02',
    groupCode: '11',
    groupName: '11 - PROFISSIONAL',
    name: 'Associações profissionais (ex: ABO, APCD)',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_11_03',
    code: '11.03',
    groupCode: '11',
    groupName: '11 - PROFISSIONAL',
    name: 'Congressos e simpósios odontológicos',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_11_04',
    code: '11.04',
    groupCode: '11',
    groupName: '11 - PROFISSIONAL',
    name: 'Cursos de aperfeiçoamento e especialização',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_11_05',
    code: '11.05',
    groupCode: '11',
    groupName: '11 - PROFISSIONAL',
    name: 'Publicações técnicas e periódicos odontológicos',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_11_06',
    code: '11.06',
    groupCode: '11',
    groupName: '11 - PROFISSIONAL',
    name: 'Hospedagem para evento profissional',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },

  // 12 - FINANCEIRO
  {
    id: 'cat_12_01',
    code: '12.01',
    groupCode: '12',
    groupName: '12 - FINANCEIRO',
    name: 'Tarifas bancárias',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_12_02',
    code: '12.02',
    groupCode: '12',
    groupName: '12 - FINANCEIRO',
    name: 'Taxas de maquininha de cartão',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_12_03',
    code: '12.03',
    groupCode: '12',
    groupName: '12 - FINANCEIRO',
    name: 'Taxas de antecipação de recebíveis',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_12_04',
    code: '12.04',
    groupCode: '12',
    groupName: '12 - FINANCEIRO',
    name: 'Juros bancários',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },
  {
    id: 'cat_12_05',
    code: '12.05',
    groupCode: '12',
    groupName: '12 - FINANCEIRO',
    name: 'Multas por atraso operacional',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },

  // 13 - TRIBUTOS
  {
    id: 'cat_13_01',
    code: '13.01',
    groupCode: '13',
    groupName: '13 - TRIBUTOS',
    name: 'DAS - Documento de Arrecadação do Simples',
    dedutivelLivroCaixaPf: 'NAO', // Tributo exclusivo da PJ
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_13_02',
    code: '13.02',
    groupCode: '13',
    groupName: '13 - TRIBUTOS',
    name: 'ISS próprio municipal',
    dedutivelLivroCaixaPf: 'SIM', // ISS do autônomo é dedutível no Livro Caixa
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_13_03',
    code: '13.03',
    groupCode: '13',
    groupName: '13 - TRIBUTOS',
    name: 'IRPF / Carnê-Leão pago',
    dedutivelLivroCaixaPf: 'NAO', // IRPF pago não deduz a si mesmo
    impactaFatorRPj: false,
    despesaOperacionalPj: false,
    active: true,
  },
  {
    id: 'cat_13_04',
    code: '13.04',
    groupCode: '13',
    groupName: '13 - TRIBUTOS',
    name: 'INSS previdenciário próprio',
    dedutivelLivroCaixaPf: 'NAO', // Não entra em Livro Caixa, mas deduz na linha oficial do Carnê-Leão
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: 'O INSS próprio não entra no Livro Caixa, mas é dedutível diretamente na ficha previdenciária oficial do Carnê-Leão.',
  },
  {
    id: 'cat_13_05',
    code: '13.05',
    groupCode: '13',
    groupName: '13 - TRIBUTOS',
    name: 'Outros tributos e taxas municipais',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: CONDITIONAL_TAX_NOTICE,
  },

  // 14 - IMOBILIZADO
  {
    id: 'cat_14_01',
    code: '14.01',
    groupCode: '14',
    groupName: '14 - IMOBILIZADO',
    name: 'Cadeira odontológica (aquisição)',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: 'Aquisição de bens do ativo imobilizado não é dedutível no Livro Caixa da PF.',
  },
  {
    id: 'cat_14_02',
    code: '14.02',
    groupCode: '14',
    groupName: '14 - IMOBILIZADO',
    name: 'Autoclave (aquisição)',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: 'Aquisição de bens duráveis não é dedutível no Livro Caixa da PF.',
  },
  {
    id: 'cat_14_03',
    code: '14.03',
    groupCode: '14',
    groupName: '14 - IMOBILIZADO',
    name: 'Compressor odontológico (aquisição)',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_14_04',
    code: '14.04',
    groupCode: '14',
    groupName: '14 - IMOBILIZADO',
    name: 'Aparelho de Raio-X (aquisição)',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_14_05',
    code: '14.05',
    groupCode: '14',
    groupName: '14 - IMOBILIZADO',
    name: 'Scanner intraoral (aquisição)',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_14_06',
    code: '14.06',
    groupCode: '14',
    groupName: '14 - IMOBILIZADO',
    name: 'Computadores e tablets',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_14_07',
    code: '14.07',
    groupCode: '14',
    groupName: '14 - IMOBILIZADO',
    name: 'Móveis para consultório e recepção',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_14_08',
    code: '14.08',
    groupCode: '14',
    groupName: '14 - IMOBILIZADO',
    name: 'Outros equipamentos duráveis',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },

  // 15 - TRANSPORTE
  {
    id: 'cat_15_01',
    code: '15.01',
    groupCode: '15',
    groupName: '15 - TRANSPORTE',
    name: 'Combustível',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
    noticeText: 'Despesas com locomoção/veículo próprio não são dedutíveis no Livro Caixa da PF.',
  },
  {
    id: 'cat_15_02',
    code: '15.02',
    groupCode: '15',
    groupName: '15 - TRANSPORTE',
    name: 'Estacionamento',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_15_03',
    code: '15.03',
    groupCode: '15',
    groupName: '15 - TRANSPORTE',
    name: 'Manutenção de veículo',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_15_04',
    code: '15.04',
    groupCode: '15',
    groupName: '15 - TRANSPORTE',
    name: 'Seguro do veículo',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_15_05',
    code: '15.05',
    groupCode: '15',
    groupName: '15 - TRANSPORTE',
    name: 'IPVA e licenciamento',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },
  {
    id: 'cat_15_06',
    code: '15.06',
    groupCode: '15',
    groupName: '15 - TRANSPORTE',
    name: 'Aplicativos de transporte (Uber, 99)',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    active: true,
  },

  // 16 - DESPESAS PESSOAIS / NÃO OPERACIONAIS
  {
    id: 'cat_16_01',
    code: '16.01',
    groupCode: '16',
    groupName: '16 - DESPESAS PESSOAIS / NÃO OPERACIONAIS',
    name: 'Retirada pessoal / Distribuição de lucros',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: false,
    active: true,
    noticeText: 'Despesas pessoais e retiradas não são dedutíveis nem operacionais.',
  },
  {
    id: 'cat_16_02',
    code: '16.02',
    groupCode: '16',
    groupName: '16 - DESPESAS PESSOAIS / NÃO OPERACIONAIS',
    name: 'Alimentação pessoal',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: false,
    active: true,
  },
  {
    id: 'cat_16_03',
    code: '16.03',
    groupCode: '16',
    groupName: '16 - DESPESAS PESSOAIS / NÃO OPERACIONAIS',
    name: 'Lazer e despesas familiares',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: false,
    active: true,
  },
  {
    id: 'cat_16_04',
    code: '16.04',
    groupCode: '16',
    groupName: '16 - DESPESAS PESSOAIS / NÃO OPERACIONAIS',
    name: 'Outras despesas não operacionais',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: false,
    active: true,
  },
];

/**
 * Standardized Initial Chart of Accounts with enriched descriptive group names.
 */
export const INITIAL_CHART_OF_ACCOUNTS: ExpenseCategory[] = RAW_CHART_OF_ACCOUNTS.map((cat) => {
  const groupDef = OPERATIONAL_EXPENSE_GROUPS[cat.groupCode];
  return {
    ...cat,
    groupName: groupDef ? groupDef.name : cat.groupName,
  };
});
