import { ClinicalRecord, ClinicalAttachment, ClinicalBeforeAfterPair } from '../types';

export const DEMO_CLINICAL_ATTACHMENTS: ClinicalAttachment[] = [
  {
    id: 'att_01',
    tenantId: 'tenant_demo',
    patientId: 'pat_01',
    clinicalRecordId: 'rec_01',
    storagePath: 'tenant_demo/patients/pat_01/clinical-records/rec_01/rx_inicial_panoramica.png',
    originalFilename: 'rx_panoramica_inicial.png',
    mimeType: 'image/png',
    sizeBytes: 2450000,
    attachmentType: 'RADIOGRAPHY',
    caption: 'Radiografia panorâmica inicial demonstrando perda óssea no elemento 36.',
    date: '2026-08-10',
    procedureName: 'Avaliação Inicial e Diagnóstico',
    createdBy: 'usr_carlos_01',
    createdAt: '2026-08-10T14:30:00.000Z',
    signedUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'att_02',
    tenantId: 'tenant_demo',
    patientId: 'pat_01',
    clinicalRecordId: 'rec_02',
    storagePath: 'tenant_demo/patients/pat_01/clinical-records/rec_02/foto_antes_clareamento.jpg',
    originalFilename: 'arcada_superior_antes.jpg',
    mimeType: 'image/jpeg',
    sizeBytes: 1850000,
    attachmentType: 'PHOTO_BEFORE',
    caption: 'Cor inicial A3.5 (Escala Vita) antes do clareamento.',
    date: '2026-08-20',
    procedureId: 'proc_01',
    procedureName: 'Clareamento Dental Combinado',
    beforeAfterPairId: 'pair_01',
    createdBy: 'usr_carlos_01',
    createdAt: '2026-08-20T10:00:00.000Z',
    signedUrl: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'att_03',
    tenantId: 'tenant_demo',
    patientId: 'pat_01',
    clinicalRecordId: 'rec_03',
    storagePath: 'tenant_demo/patients/pat_01/clinical-records/rec_03/foto_depois_clareamento.jpg',
    originalFilename: 'arcada_superior_depois.jpg',
    mimeType: 'image/jpeg',
    sizeBytes: 1920000,
    attachmentType: 'PHOTO_AFTER',
    caption: 'Resultado final após 3 sessões: tom B1 estabilizado.',
    date: '2026-09-15',
    procedureId: 'proc_01',
    procedureName: 'Clareamento Dental Combinado',
    beforeAfterPairId: 'pair_01',
    createdBy: 'usr_carlos_01',
    createdAt: '2026-09-15T11:15:00.000Z',
    signedUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'att_04',
    tenantId: 'tenant_demo',
    patientId: 'pat_01',
    clinicalRecordId: 'rec_02',
    storagePath: 'tenant_demo/patients/pat_01/clinical-records/rec_02/termo_consentimento_clareamento.pdf',
    originalFilename: 'termo_consentimento_esclarecido.pdf',
    mimeType: 'application/pdf',
    sizeBytes: 420000,
    attachmentType: 'CONSENT_FORM',
    caption: 'Termo de consentimento livre e esclarecido devidamente assinado pela paciente.',
    date: '2026-08-20',
    procedureName: 'Clareamento Dental Combinado',
    createdBy: 'usr_carlos_01',
    createdAt: '2026-08-20T10:05:00.000Z',
  },
];

export const DEMO_BEFORE_AFTER_PAIRS: ClinicalBeforeAfterPair[] = [
  {
    id: 'pair_01',
    tenantId: 'tenant_demo',
    patientId: 'pat_01',
    title: 'Clareamento Dental em Consultório + Caseiro',
    procedureName: 'Clareamento Dental Combinado',
    observation: 'Evolução de 4 tons na escala Vita (de A3.5 para B1) sem sensibilidade pós-operatória.',
    beforeAttachmentId: 'att_02',
    afterAttachmentId: 'att_03',
    beforeAttachment: DEMO_CLINICAL_ATTACHMENTS[1],
    afterAttachment: DEMO_CLINICAL_ATTACHMENTS[2],
    beforeDate: '2026-08-20',
    afterDate: '2026-09-15',
    createdBy: 'usr_carlos_01',
    createdAt: '2026-09-15T11:30:00.000Z',
  },
];

export const DEMO_CLINICAL_RECORDS: ClinicalRecord[] = [
  {
    id: 'rec_03',
    tenantId: 'tenant_demo',
    patientId: 'pat_01',
    professionalId: 'prof_mendes_01',
    professionalName: 'Dr. Carlos Eduardo Mendes',
    professionalCro: 'CRO-SP 98765',
    recordType: 'CONCLUSAO',
    procedureId: 'proc_01',
    procedureName: 'Clareamento Dental Combinado',
    recordDate: '2026-09-15',
    recordTime: '11:00',
    complaint: 'Retorno para avaliação final e polimento pós-clareamento.',
    assessment: 'Gengiva sadia, sem sinais de irritação química. Resultado estético harmônico atingido.',
    conduct: 'Polimento final com discos de feltro e pasta diamantada. Aplicação tópica de flúor neutro.',
    evolution: 'Paciente relatou total satisfação com o resultado estético. Ausência de dor ou sensibilidade ao ar ou frio.',
    conclusion: 'Tratamento de clareamento concluído com êxito.',
    guidance: 'Evitar alimentos com corantes intensos (café, vinho tinto, molho de tomate) nas primeiras 48h. Manter escovação adequada.',
    returnDate: '2027-03-15',
    status: 'FINALIZED',
    attachmentsCount: 1,
    attachments: [DEMO_CLINICAL_ATTACHMENTS[2]],
    amendments: [],
    createdBy: 'usr_carlos_01',
    createdByName: 'Dr. Carlos Eduardo Mendes',
    createdAt: '2026-09-15T11:20:00.000Z',
    finalizedBy: 'usr_carlos_01',
    finalizedByName: 'Dr. Carlos Eduardo Mendes',
    finalizedAt: '2026-09-15T11:25:00.000Z',
  },
  {
    id: 'rec_02',
    tenantId: 'tenant_demo',
    patientId: 'pat_01',
    professionalId: 'prof_mendes_01',
    professionalName: 'Dr. Carlos Eduardo Mendes',
    professionalCro: 'CRO-SP 98765',
    recordType: 'PROCEDIMENTO',
    procedureId: 'proc_01',
    procedureName: 'Clareamento Dental Combinado',
    recordDate: '2026-08-20',
    recordTime: '09:30',
    complaint: 'Início da 1ª sessão de clareamento em consultório.',
    assessment: 'Dentes hígidos, ausência de lesões cervicais não cariosas expostas.',
    conduct: 'Isolamento relativo com barreira gengival fotopolimerizável. Aplicação de Peróxido de Hidrogênio a 35% por 40 minutos.',
    evolution: 'Sessão transcorreu sem intercorrências. Cor inicial fotografada e registrada.',
    conclusion: 'Primeira etapa concluída. Entregues moldeiras e gel a 10% para uso noturno.',
    guidance: 'Uso de dessensibilizante se necessário. Não fumar.',
    returnDate: '2026-09-05',
    status: 'AMENDED',
    attachmentsCount: 2,
    attachments: [DEMO_CLINICAL_ATTACHMENTS[1], DEMO_CLINICAL_ATTACHMENTS[3]],
    amendments: [
      {
        id: 'amen_01',
        tenantId: 'tenant_demo',
        clinicalRecordId: 'rec_02',
        reason: 'Complemento de dosagem do gel caseiro',
        content: 'Retificação: Foi entregue 1 seringa extra de Peróxido de Carbamida 10% e orientado uso por 2 horas diárias ao invés de noturno devido a bruxismo leve.',
        createdBy: 'usr_carlos_01',
        createdByName: 'Dr. Carlos Eduardo Mendes',
        createdAt: '2026-08-20T17:00:00.000Z',
      },
    ],
    createdBy: 'usr_carlos_01',
    createdByName: 'Dr. Carlos Eduardo Mendes',
    createdAt: '2026-08-20T10:15:00.000Z',
    finalizedBy: 'usr_carlos_01',
    finalizedByName: 'Dr. Carlos Eduardo Mendes',
    finalizedAt: '2026-08-20T10:30:00.000Z',
  },
  {
    id: 'rec_01',
    tenantId: 'tenant_demo',
    patientId: 'pat_01',
    professionalId: 'prof_mendes_01',
    professionalName: 'Dr. Carlos Eduardo Mendes',
    professionalCro: 'CRO-SP 98765',
    recordType: 'AVALIACAO',
    recordDate: '2026-08-10',
    recordTime: '14:00',
    complaint: 'Paciente queixa-se de dentes amarelados e desconforto mastigatório leve no quadrante inferior esquerdo.',
    assessment: 'Dentição completa. Elemento 36 com restauração antiga infiltrada sem comprometimento pulpar.',
    conduct: 'Exame clínico minucioso, tomada de radiografia panorâmica e sondagem periodontal.',
    evolution: 'Apresentado plano de tratamento multidisciplinar: 1) Clareamento estético, 2) Substituição de restauração no 36.',
    conclusion: 'Paciente de acordo com o planejamento e cronograma sugerido.',
    guidance: 'Agendada profilaxia prévia e primeira sessão de clareamento.',
    returnDate: '2026-08-20',
    status: 'FINALIZED',
    attachmentsCount: 1,
    attachments: [DEMO_CLINICAL_ATTACHMENTS[0]],
    amendments: [],
    createdBy: 'usr_carlos_01',
    createdByName: 'Dr. Carlos Eduardo Mendes',
    createdAt: '2026-08-10T14:45:00.000Z',
    finalizedBy: 'usr_carlos_01',
    finalizedByName: 'Dr. Carlos Eduardo Mendes',
    finalizedAt: '2026-08-10T15:00:00.000Z',
  },
];
