import {
  Organization,
  User,
  Professional,
  Patient,
  Sale,
  Expense,
  BankAccount,
  PayrollHistoryEntry,
  DentalProcedure,
  ClinicalInput,
  Appointment,
} from '../types';

export const DEMO_ORGANIZATION: Organization = {
  id: 'org_mendes_01',
  name: 'Mendes Odontologia Integrada',
  tradeName: 'Mendes Odonto',
  createdAt: '2024-01-10T10:00:00Z',
};

export const DEMO_USER: User = {
  id: 'usr_carlos_01',
  orgId: 'org_mendes_01',
  name: 'Dr. Carlos Eduardo Mendes',
  email: 'dr.carlos@mendesodonto.com.br',
  role: 'OWNER',
};

export const DEMO_PROFESSIONAL: Professional = {
  id: 'prof_mendes_01',
  orgId: 'org_mendes_01',
  name: 'Dr. Carlos Eduardo Mendes',
  cpf: '12845678901',
  cro: '98765',
  croUf: 'SP',
  cnpj: '38123456000189',
  razaoSocial: 'Carlos E. Mendes Odontologia Ltda ME',
  nomeFantasia: 'Mendes Odontologia',
  municipio: 'São Paulo - SP',
  regimeTributario: 'SIMPLES_NACIONAL',
  optanteSimples: true,
  dataAbertura: '2022-03-15',
  rbt12Inicial: 280000.00, // R$ 280.000,00 nos últimos 12 meses
  folha12MesesInicial: 84000.00, // R$ 84.000,00 nos últimos 12 meses -> Fator R inicial = 30% (Anexo III)
  proLaboreMensal: 4500.00,
  baselineConfigured: true,
  numDependentes: 1, // Dedução PF: 1 dependente = R$ 189,59/mês
  inssProprioMensal: 950.00, // Previdência oficial própria autônomo
  outrosRendimentosTributaveis: 0,
};

export const DEMO_BANK_ACCOUNTS: BankAccount[] = [
  {
    id: 'bank_01',
    orgId: 'org_mendes_01',
    name: 'Itaú CPF',
    bankName: 'Itaú',
    accountType: 'CORRENTE_PF',
    initialBalance: 14500.00,
    currentBalance: 18250.00,
    isPreferred: true,
  },
  {
    id: 'bank_02',
    orgId: 'org_mendes_01',
    name: 'Santander PJ',
    bankName: 'Santander',
    accountType: 'CORRENTE_PJ',
    initialBalance: 32000.00,
    currentBalance: 46800.00,
  },
];

export const DEMO_PROCEDURES: DentalProcedure[] = [
  {
    id: 'proc_01',
    code: 'PROC-01',
    name: 'Restauração em Resina Composta (1 Face)',
    category: 'Dentística',
    description: 'Restauração direta de dente posterior ou anterior com resina microhíbrida/nanoparticulada',
    clinicalDurationMinutes: 45,
    professionalHourlyRate: 150,
    professionalCost: 112.50,
    inputs: [
      { id: 'inp_1', name: 'Resina Composta Filtek Z350 XT', unit: 'porção', quantity: 1, unitCost: 18.00, totalCost: 18.00 },
      { id: 'inp_2', name: 'Ácido Fosfórico 37% + Adesivo Single Bond', unit: 'kit', quantity: 1, unitCost: 6.50, totalCost: 6.50 },
      { id: 'inp_3', name: 'Tubete Anestésico Mepivacaína 2%', unit: 'un', quantity: 1, unitCost: 7.50, totalCost: 7.50 },
      { id: 'inp_4', name: 'Kit Biossegurança / EPI descartável', unit: 'kit', quantity: 1, unitCost: 9.00, totalCost: 9.00 },
      { id: 'inp_5', name: 'Matriz de aço + Cunha anatômica', unit: 'par', quantity: 1, unitCost: 4.00, totalCost: 4.00 },
    ],
    inputsCost: 45.00,
    labCost: 0,
    otherCosts: 10.00,
    totalCost: 167.50,
    targetMarginPercent: 50,
    estimatedTaxesPercent: 6,
    suggestedPrice: 380.00,
    defaultPrice: 380.00,
    active: true,
  },
  {
    id: 'proc_02',
    code: 'PROC-02',
    name: 'Tratamento Endodôntico (Canal Molar - 3 canais)',
    category: 'Endodontia',
    description: 'Biopulpectomia / necropulpectomia de molar com instrumentação rotatória e obturação termoplastificada',
    clinicalDurationMinutes: 90,
    professionalHourlyRate: 150,
    professionalCost: 225.00,
    inputs: [
      { id: 'inp_21', name: 'Kit Limas Rotatórias WaveOne Gold (desgaste/uso)', unit: 'kit', quantity: 1, unitCost: 65.00, totalCost: 65.00 },
      { id: 'inp_22', name: 'Tubetes Anestésicos Articaína 4% com Epinefrina', unit: 'un', quantity: 2, unitCost: 11.00, totalCost: 22.00 },
      { id: 'inp_23', name: 'Hipoclorito de Sódio 2.5% + EDTA 17%', unit: 'ml', quantity: 20, unitCost: 0.60, totalCost: 12.00 },
      { id: 'inp_24', name: 'Cones de Guta-percha + Cimento Endodôntico AH Plus', unit: 'kit', quantity: 1, unitCost: 28.00, totalCost: 28.00 },
      { id: 'inp_25', name: 'Kit Isolamento Absoluto (Lençol, grampo, arco)', unit: 'kit', quantity: 1, unitCost: 18.00, totalCost: 18.00 },
    ],
    inputsCost: 145.00,
    labCost: 0,
    otherCosts: 30.00,
    totalCost: 400.00,
    targetMarginPercent: 60,
    estimatedTaxesPercent: 6,
    suggestedPrice: 1200.00,
    defaultPrice: 1200.00,
    active: true,
  },
  {
    id: 'proc_03',
    code: 'PROC-03',
    name: 'Implante Dentário Cone Morse com Biomaterial',
    category: 'Implantodontia',
    description: 'Instalação cirúrgica de implante de titânio conexão Cone Morse com enxerto ósseo particulado',
    clinicalDurationMinutes: 60,
    professionalHourlyRate: 250,
    professionalCost: 250.00,
    inputs: [
      { id: 'inp_31', name: 'Implante Dentário Titânio Neodent/Straumann CM', unit: 'un', quantity: 1, unitCost: 480.00, totalCost: 480.00 },
      { id: 'inp_32', name: 'Biomaterial Ósseo Liofilizado + Membrana Colágeno', unit: 'kit', quantity: 1, unitCost: 280.00, totalCost: 280.00 },
      { id: 'inp_33', name: 'Kit Cirúrgico Estéril Completo Drapeado', unit: 'kit', quantity: 1, unitCost: 55.00, totalCost: 55.00 },
      { id: 'inp_34', name: 'Anestésicos e Fio de Sutura Cirúrgico Nylon 5-0', unit: 'un', quantity: 1, unitCost: 35.00, totalCost: 35.00 },
    ],
    inputsCost: 850.00,
    labCost: 0,
    otherCosts: 60.00,
    totalCost: 1160.00,
    targetMarginPercent: 55,
    estimatedTaxesPercent: 6,
    suggestedPrice: 2800.00,
    defaultPrice: 2800.00,
    active: true,
  },
  {
    id: 'proc_04',
    code: 'PROC-04',
    name: 'Prótese Fixa em Zircônia Sobre Implante',
    category: 'Prótese',
    description: 'Confecção e instalação de coroa protética personalizada em Zircônia fresada CAD/CAM',
    clinicalDurationMinutes: 45,
    professionalHourlyRate: 200,
    professionalCost: 150.00,
    inputs: [
      { id: 'inp_41', name: 'Transferente, Análogo e Parafuso de Titânio', unit: 'kit', quantity: 1, unitCost: 120.00, totalCost: 120.00 },
      { id: 'inp_42', name: 'Silicone de Adição Leve/Pesado para Moldagem', unit: 'kit', quantity: 1, unitCost: 55.00, totalCost: 55.00 },
      { id: 'inp_43', name: 'Cimento Resinoso Dual Autoadesivo RelyX', unit: 'aplicação', quantity: 1, unitCost: 35.00, totalCost: 35.00 },
    ],
    inputsCost: 210.00,
    labCost: 480.00,
    otherCosts: 30.00,
    totalCost: 870.00,
    targetMarginPercent: 60,
    estimatedTaxesPercent: 6,
    suggestedPrice: 2400.00,
    defaultPrice: 2400.00,
    active: true,
  },
  {
    id: 'proc_05',
    code: 'PROC-05',
    name: 'Profilaxia e Raspagem Supragengival com Jato',
    category: 'Periodontia',
    description: 'Limpeza profissional, raspagem de cálculo supragengival, profilaxia com bicarbonato e aplicação tópica de flúor',
    clinicalDurationMinutes: 30,
    professionalHourlyRate: 150,
    professionalCost: 75.00,
    inputs: [
      { id: 'inp_51', name: 'Pasta Profilática com Flúor + Taça de Borracha', unit: 'un', quantity: 1, unitCost: 12.00, totalCost: 12.00 },
      { id: 'inp_52', name: 'Pó de Bicarbonato Especial para Profilaxia', unit: 'dose', quantity: 1, unitCost: 8.00, totalCost: 8.00 },
      { id: 'inp_53', name: 'Flúor Fosfato Acidulado em Gel 1.23%', unit: 'aplicação', quantity: 1, unitCost: 6.00, totalCost: 6.00 },
      { id: 'inp_54', name: 'Kit Descartável (Sugador, babador, luvas, máscara)', unit: 'kit', quantity: 1, unitCost: 9.00, totalCost: 9.00 },
    ],
    inputsCost: 35.00,
    labCost: 0,
    otherCosts: 15.00,
    totalCost: 125.00,
    targetMarginPercent: 55,
    estimatedTaxesPercent: 6,
    suggestedPrice: 290.00,
    defaultPrice: 290.00,
    active: true,
  },
  {
    id: 'proc_06',
    code: 'PROC-06',
    name: 'Extração de Terceiro Molar Incluso (Siso Complexo)',
    category: 'Cirurgia',
    description: 'Exodontia cirúrgica de terceiro molar impactado com odontossecção, osteotomia e sutura',
    clinicalDurationMinutes: 60,
    professionalHourlyRate: 180,
    professionalCost: 180.00,
    inputs: [
      { id: 'inp_61', name: 'Tubetes Anestésicos Articaína 4% com Epinefrina', unit: 'un', quantity: 2, unitCost: 11.00, totalCost: 22.00 },
      { id: 'inp_62', name: 'Lâmina de Bisturi 15C + Fio de Seda 4-0', unit: 'kit', quantity: 1, unitCost: 18.00, totalCost: 18.00 },
      { id: 'inp_63', name: 'Broca Cirúrgica Zecrya Alta Rotação (desgaste)', unit: 'un', quantity: 1, unitCost: 45.00, totalCost: 45.00 },
      { id: 'inp_64', name: 'Esponja Hemostática de Colágeno Hemopon', unit: 'un', quantity: 1, unitCost: 25.00, totalCost: 25.00 },
    ],
    inputsCost: 110.00,
    labCost: 0,
    otherCosts: 30.00,
    totalCost: 320.00,
    targetMarginPercent: 55,
    estimatedTaxesPercent: 6,
    suggestedPrice: 750.00,
    defaultPrice: 750.00,
    active: true,
  },
  {
    id: 'proc_07',
    code: 'PROC-07',
    name: 'Clareamento Dental de Consultório (Laser/LED)',
    category: 'Estética',
    description: 'Sessão clínica de clareamento com peróxido de hidrogênio 35% ativado por luz e barreira gengival',
    clinicalDurationMinutes: 60,
    professionalHourlyRate: 180,
    professionalCost: 180.00,
    inputs: [
      { id: 'inp_71', name: 'Gel Peróxido de Hidrogênio 35% Whiteness HP AutoMix', unit: 'dose', quantity: 1, unitCost: 140.00, totalCost: 140.00 },
      { id: 'inp_72', name: 'Barreira Gengival Fotopolimerizável Top Dam', unit: 'aplicação', quantity: 1, unitCost: 25.00, totalCost: 25.00 },
      { id: 'inp_73', name: 'Gel Dessensibilizante KF 2%', unit: 'dose', quantity: 1, unitCost: 18.00, totalCost: 18.00 },
      { id: 'inp_74', name: 'Afastador Labial ArcFlex + Kit descartável', unit: 'kit', quantity: 1, unitCost: 20.00, totalCost: 20.00 },
    ],
    inputsCost: 203.00,
    labCost: 0,
    otherCosts: 25.00,
    totalCost: 408.00,
    targetMarginPercent: 65,
    estimatedTaxesPercent: 6,
    suggestedPrice: 1400.00,
    defaultPrice: 1400.00,
    active: true,
  },
  {
    id: 'proc_08',
    code: 'PROC-08',
    name: 'Alinhador Invisível - Manutenção / Parcela',
    category: 'Ortodontia',
    description: 'Consulta de acompanhamento, troca de alinhador ortodôntico transparente e desgaste interproximal (IPR)',
    clinicalDurationMinutes: 30,
    professionalHourlyRate: 150,
    professionalCost: 75.00,
    inputs: [
      { id: 'inp_81', name: 'Kit Attachments em Resina Flow + Molde guia', unit: 'kit', quantity: 1, unitCost: 45.00, totalCost: 45.00 },
      { id: 'inp_82', name: 'Tiras diamantadas para IPR', unit: 'un', quantity: 2, unitCost: 15.00, totalCost: 30.00 },
      { id: 'inp_83', name: 'Kit Biossegurança', unit: 'kit', quantity: 1, unitCost: 10.00, totalCost: 10.00 },
    ],
    inputsCost: 85.00,
    labCost: 350.00, // Custo do alinhador ortodôntico
    otherCosts: 20.00,
    totalCost: 530.00,
    targetMarginPercent: 40,
    estimatedTaxesPercent: 6,
    suggestedPrice: 950.00,
    defaultPrice: 950.00,
    active: true,
  },
  {
    id: 'proc_09',
    code: 'PROC-09',
    name: 'Faceta em Resina / Cerâmica Estética',
    category: 'Estética',
    description: 'Estratificação direta anatômica de faceta dental com resinas de esmalte, corpo e efeitos translúcidos',
    clinicalDurationMinutes: 75,
    professionalHourlyRate: 200,
    professionalCost: 250.00,
    inputs: [
      { id: 'inp_91', name: 'Resina Composta de Estratificação Tokuyama Estelite Omega', unit: 'porção', quantity: 1, unitCost: 80.00, totalCost: 80.00 },
      { id: 'inp_92', name: 'Discos Sof-Lex + Pontas Espirais de Polimento Diamond', unit: 'kit', quantity: 1, unitCost: 45.00, totalCost: 45.00 },
      { id: 'inp_93', name: 'Pasta Diamantada de Brilho Enamelize', unit: 'dose', quantity: 1, unitCost: 20.00, totalCost: 20.00 },
      { id: 'inp_94', name: 'Kit Isolamento Absoluto e Matriz TDV', unit: 'kit', quantity: 1, unitCost: 15.00, totalCost: 15.00 },
    ],
    inputsCost: 160.00,
    labCost: 0,
    otherCosts: 25.00,
    totalCost: 435.00,
    targetMarginPercent: 70,
    estimatedTaxesPercent: 6,
    suggestedPrice: 1600.00,
    defaultPrice: 1600.00,
    active: true,
  },
  {
    id: 'proc_10',
    code: 'PROC-10',
    name: 'Coroa Metalocerâmica Cimentada',
    category: 'Prótese',
    description: 'Preparo protético, moldagem de precisão, confecção e cimentação de coroa sobre dente preparado',
    clinicalDurationMinutes: 60,
    professionalHourlyRate: 150,
    professionalCost: 150.00,
    inputs: [
      { id: 'inp_101', name: 'Silicone de Condensação / Adição + Fio Retrator', unit: 'kit', quantity: 1, unitCost: 45.00, totalCost: 45.00 },
      { id: 'inp_102', name: 'Resina Acrílica para Provisório Duralay', unit: 'dose', quantity: 1, unitCost: 25.00, totalCost: 25.00 },
      { id: 'inp_103', name: 'Cimento de Fosfato de Zinco / Resinoso', unit: 'dose', quantity: 1, unitCost: 20.00, totalCost: 20.00 },
    ],
    inputsCost: 90.00,
    labCost: 380.00, // Custo laboratorial da metalocerâmica
    otherCosts: 25.00,
    totalCost: 645.00,
    targetMarginPercent: 55,
    estimatedTaxesPercent: 6,
    suggestedPrice: 1500.00,
    defaultPrice: 1500.00,
    active: true,
  },
];

export const DEMO_CLINICAL_INPUTS: ClinicalInput[] = [
  // 1. ANESTÉSICOS (tubete)
  {
    id: 'inp_articaína_50',
    name: 'Anestésico Articaína 4% c/ Epinefrina 1:100.000',
    brand: 'DFL - Articaine',
    category: 'Anestésicos',
    purchasePackageName: 'Caixa c/ 50 tubetes de vidro',
    packageQuantity: 50,
    purchasePrice: 140.00,
    purchaseUnitType: 'tubete',
    usageUnit: 'tubete',
    unitCost: 2.80, // R$ 140 / 50 = R$ 2,80 por tubete
    active: true,
    notes: 'Anestésico de alta difusão tecidual para procedimentos cirúrgicos e endodônticos.',
  },
  {
    id: 'inp_lidocaína_50',
    name: 'Anestésico Lidocaína 2% c/ Epinefrina 1:100.000',
    brand: 'Alphacaine / DFL',
    category: 'Anestésicos',
    purchasePackageName: 'Caixa c/ 50 tubetes',
    packageQuantity: 50,
    purchasePrice: 110.00,
    purchaseUnitType: 'tubete',
    usageUnit: 'tubete',
    unitCost: 2.20, // R$ 110 / 50 = R$ 2,20 por tubete
    active: true,
  },
  {
    id: 'inp_mepivacaína_50',
    name: 'Anestésico Mepivacaína 3% sem vasoconstritor',
    brand: 'DFL / Mepisv',
    category: 'Anestésicos',
    purchasePackageName: 'Caixa c/ 50 tubetes',
    packageQuantity: 50,
    purchasePrice: 150.00,
    purchaseUnitType: 'tubete',
    usageUnit: 'tubete',
    unitCost: 3.00, // R$ 150 / 50 = R$ 3,00 por tubete
    active: true,
    notes: 'Indicado para pacientes cardiopatas ou hipertensos descompensados.',
  },

  // 2. LÍQUIDOS (ml / Litro)
  {
    id: 'inp_clorexidina_1l',
    name: 'Clorexidina 2% Solução Aquosa',
    brand: 'Vic Pharma / Rioquímica',
    category: 'Biossegurança',
    purchasePackageName: 'Frasco de 1 Litro (1000 ml)',
    packageQuantity: 1000,
    purchasePrice: 45.00,
    purchaseUnitType: 'L',
    usageUnit: 'ml',
    unitCost: 0.045, // R$ 45,00 / 1000 ml = R$ 0,045/ml (20 ml no bochecho prévio = R$ 0,90)
    active: true,
    notes: 'Antisséptico pré-operatório. 1 Litro = 1000 ml. Bochecho padrão usa 15 a 20 ml.',
  },
  {
    id: 'inp_alcool_70_1l',
    name: 'Álcool 70% Hospitalar para Desinfecção',
    brand: 'Rioquímica',
    category: 'Biossegurança',
    purchasePackageName: 'Frasco de 1 Litro (1000 ml)',
    packageQuantity: 1000,
    purchasePrice: 18.00,
    purchaseUnitType: 'L',
    usageUnit: 'ml',
    unitCost: 0.018, // R$ 18,00 / 1000 ml = R$ 0,018/ml (50 ml na bancada = R$ 0,90)
    active: true,
  },
  {
    id: 'inp_hipoclorito_1l',
    name: 'Hipoclorito de Sódio 2,5% Solução Irrigadora',
    brand: 'Biodinâmica',
    category: 'Endodontia',
    purchasePackageName: 'Frasco de 1000 ml',
    packageQuantity: 1000,
    purchasePrice: 32.00,
    purchaseUnitType: 'ml',
    usageUnit: 'ml',
    unitCost: 0.032, // R$ 32,00 / 1000 ml = R$ 0,032/ml (30 ml no canal = R$ 0,96)
    active: true,
  },

  // 3. SÓLIDOS, PASTAS E RESINAS (g / kg)
  {
    id: 'inp_resina_z350',
    name: 'Resina Nanohíbrida Filtek Z350 XT',
    brand: '3M ESPE',
    category: 'Dentística',
    purchasePackageName: 'Seringa de 4 g',
    packageQuantity: 4,
    purchasePrice: 128.00,
    purchaseUnitType: 'g',
    usageUnit: 'g',
    unitCost: 32.00, // R$ 128,00 / 4 g = R$ 32,00 por grama (0.25 g na restauração 1 face = R$ 8,00)
    active: true,
    notes: 'Restaurações estéticas diretas anteriores e posteriores.',
  },
  {
    id: 'inp_resina_flow',
    name: 'Resina Composta Fluida Filtek Flow',
    brand: '3M ESPE',
    category: 'Dentística',
    purchasePackageName: 'Seringa de 2 g',
    packageQuantity: 2,
    purchasePrice: 72.00,
    purchaseUnitType: 'g',
    usageUnit: 'g',
    unitCost: 36.00, // R$ 72 / 2 = R$ 36,00/g (0.1 g em forramento = R$ 3,60)
    active: true,
  },
  {
    id: 'inp_gesso_pedra_iv',
    name: 'Gesso Pedra Especial Tipo IV',
    brand: 'Polidental / GC Fujirock',
    category: 'Prótese',
    purchasePackageName: 'Saco de 1 kg (1000 g)',
    packageQuantity: 1000,
    purchasePrice: 48.00,
    purchaseUnitType: 'kg',
    usageUnit: 'g',
    unitCost: 0.048, // R$ 48 / 1000 g = R$ 0,048/g (100 g para vazamento de modelo = R$ 4,80)
    active: true,
  },
  {
    id: 'inp_alginato_jeltrate',
    name: 'Alginato para Moldagem Jeltrate Plus',
    brand: 'Dentsply Sirona',
    category: 'Moldagem',
    purchasePackageName: 'Pacote de 454 g',
    packageQuantity: 454,
    purchasePrice: 54.00,
    purchaseUnitType: 'g',
    usageUnit: 'g',
    unitCost: 0.119, // R$ 54 / 454 g = R$ 0,119/g (20 g para moldagem arcada = R$ 2,38)
    active: true,
  },

  // 4. DOSES E APLICAÇÕES (dose)
  {
    id: 'inp_adesivo_singlebond',
    name: 'Adesivo Monocomponente Single Bond Universal',
    brand: '3M ESPE',
    category: 'Dentística',
    purchasePackageName: 'Frasco de 5 ml (~160 gotas/doses)',
    packageQuantity: 160,
    purchasePrice: 176.00,
    purchaseUnitType: 'dose',
    usageUnit: 'dose',
    unitCost: 1.10, // R$ 176 / 160 doses = R$ 1,10 por dose/gota
    active: true,
    notes: 'Adesivo fotopolimerizável com silano integrado.',
  },
  {
    id: 'inp_acido_fosforico',
    name: 'Ácido Fosfórico 37% Condicionador Dental',
    brand: 'FGM / Condac 37',
    category: 'Dentística',
    purchasePackageName: 'Seringa de 3 ml com ponteiras (~40 aplicações)',
    packageQuantity: 40,
    purchasePrice: 24.00,
    purchaseUnitType: 'dose',
    usageUnit: 'dose',
    unitCost: 0.60, // R$ 24 / 40 doses = R$ 0,60 por aplicação
    active: true,
  },
  {
    id: 'inp_fluor_varnish',
    name: 'Verniz Fluoretado Duraphat 5%',
    brand: 'Colgate Oral Care',
    category: 'Preventiva',
    purchasePackageName: 'Tubo de 10 ml (~30 aplicações)',
    packageQuantity: 30,
    purchasePrice: 90.00,
    purchaseUnitType: 'dose',
    usageUnit: 'dose',
    unitCost: 3.00, // R$ 90 / 30 = R$ 3,00 por aplicação
    active: true,
  },

  // 5. KITS (kit)
  {
    id: 'inp_kit_cirurgico',
    name: 'Kit Cirúrgico Estéril Descartável Completo',
    brand: 'Polar Fix / Descarpack',
    category: 'Cirurgia',
    purchasePackageName: 'Fardo c/ 10 kits embalados individualmente',
    packageQuantity: 10,
    purchasePrice: 160.00,
    purchaseUnitType: 'kit',
    usageUnit: 'kit',
    unitCost: 16.00, // R$ 160 / 10 = R$ 16,00 por kit
    active: true,
    notes: 'Contém 2 aventais cirúrgicos 40g, 2 campos de mesa, 1 campo fenestrado e protetores de mangueira.',
  },
  {
    id: 'inp_kit_biosseguranca',
    name: 'Kit Biossegurança / EPI Descartável Básico',
    brand: 'Protéc / Medix',
    category: 'Biossegurança',
    purchasePackageName: 'Pacote com 20 kits simples',
    packageQuantity: 20,
    purchasePrice: 180.00,
    purchaseUnitType: 'kit',
    usageUnit: 'kit',
    unitCost: 9.00, // R$ 180 / 20 = R$ 9,00 por kit
    active: true,
  },
  {
    id: 'inp_kit_clareamento_caseiro',
    name: 'Kit Clareamento Caseiro Whiteness Perfect 16%',
    brand: 'FGM Dental',
    category: 'Estética',
    purchasePackageName: 'Kit completo com 5 seringas e estojo de moldeira',
    packageQuantity: 1,
    purchasePrice: 135.00,
    purchaseUnitType: 'kit',
    usageUnit: 'kit',
    unitCost: 135.00,
    active: true,
  },

  // 6. UNIDADES E PEÇAS (un)
  {
    id: 'inp_luvas_nitrilicas',
    name: 'Luvas de Procedimento Nitrílicas sem Pó (Par)',
    brand: 'Supermax / Unigloves',
    category: 'Biossegurança',
    purchasePackageName: 'Caixa com 100 luvas (50 pares)',
    packageQuantity: 50,
    purchasePrice: 48.00,
    purchaseUnitType: 'un',
    usageUnit: 'un',
    unitCost: 0.96, // R$ 48 / 50 pares = R$ 0,96 por par de luvas
    active: true,
    notes: 'Custo calculado por par utilizado pelo cirurgião-dentista ou auxiliar.',
  },
  {
    id: 'inp_mascara_tripla',
    name: 'Máscara Cirúrgica Descartável Tripla c/ Filtro',
    brand: 'Descarpack',
    category: 'Biossegurança',
    purchasePackageName: 'Caixa com 50 unidades',
    packageQuantity: 50,
    purchasePrice: 20.00,
    purchaseUnitType: 'un',
    usageUnit: 'un',
    unitCost: 0.40, // R$ 20 / 50 = R$ 0,40 por unidade
    active: true,
  },
  {
    id: 'inp_sugador_descartavel',
    name: 'Sugador Descartável Odontológico c/ Ponteira Macia',
    brand: 'SS White / Maquira',
    category: 'Biossegurança',
    purchasePackageName: 'Pacote com 40 unidades',
    packageQuantity: 40,
    purchasePrice: 16.00,
    purchaseUnitType: 'un',
    usageUnit: 'un',
    unitCost: 0.40, // R$ 16 / 40 = R$ 0,40 por unidade
    active: true,
  },
  {
    id: 'inp_babador_impermeavel',
    name: 'Babador Descartável Impermeável',
    brand: 'Allprime / TDV',
    category: 'Biossegurança',
    purchasePackageName: 'Pacote com 100 unidades',
    packageQuantity: 100,
    purchasePrice: 28.00,
    purchaseUnitType: 'un',
    usageUnit: 'un',
    unitCost: 0.28, // R$ 28 / 100 = R$ 0,28 por unidade
    active: true,
  },
  {
    id: 'inp_lamina_bisturi_15',
    name: 'Lâmina de Bisturi em Aço Carbono nº 15',
    brand: 'Swann-Morton / Wiltex',
    category: 'Cirurgia',
    purchasePackageName: 'Caixa com 100 unidades estéreis',
    packageQuantity: 100,
    purchasePrice: 60.00,
    purchaseUnitType: 'un',
    usageUnit: 'un',
    unitCost: 0.60, // R$ 60 / 100 = R$ 0,60 por lâmina
    active: true,
  },
  {
    id: 'inp_fio_sutura_seda',
    name: 'Fio de Sutura Seda Trançada 3-0 com Agulha',
    brand: 'Ethicon / Procare',
    category: 'Cirurgia',
    purchasePackageName: 'Caixa com 24 envelopes estéreis',
    packageQuantity: 24,
    purchasePrice: 72.00,
    purchaseUnitType: 'un',
    usageUnit: 'un',
    unitCost: 3.00, // R$ 72 / 24 = R$ 3,00 por envelope
    active: true,
  },
  {
    id: 'inp_broca_diamantada',
    name: 'Broca Diamantada Alta Rotação (Depreciação por uso)',
    brand: 'KG Sorensen',
    category: 'Dentística',
    purchasePackageName: 'Embalagem unitária (vida útil estimada: 5 preparos)',
    packageQuantity: 5,
    purchasePrice: 18.00,
    purchaseUnitType: 'un',
    usageUnit: 'un',
    unitCost: 3.60, // R$ 18 / 5 preparos = R$ 3,60 por uso
    active: true,
  },
];

export const DEMO_PATIENTS: Patient[] = [
  {
    id: 'pat_01',
    orgId: 'org_mendes_01',
    name: 'Mariana Santos Lima',
    cpf: '21948375120',
    email: 'mariana.lima@exemplo.com.br',
    phone: '(11) 98765-4321',
    birthDate: '1989-04-12',
    createdAt: '2024-02-15',
  },
  {
    id: 'pat_02',
    orgId: 'org_mendes_01',
    name: 'Rodrigo Alves Ribeiro',
    cpf: '34819264035',
    email: 'rodrigo.ribeiro@exemplo.com.br',
    phone: '(11) 99123-4567',
    birthDate: '1982-11-23',
    createdAt: '2024-03-01',
  },
  {
    id: 'pat_03',
    orgId: 'org_mendes_01',
    name: 'Camila Beatriz Duarte',
    cpf: '45920384752',
    email: 'camila.duarte@exemplo.com.br',
    phone: '(11) 97456-1234',
    birthDate: '1995-07-08',
    createdAt: '2024-04-10',
  },
  {
    id: 'pat_04',
    orgId: 'org_mendes_01',
    name: 'Lucas Fernando Rocha (Menor)',
    cpf: '56031495863',
    email: 'lucas.rocha@exemplo.com.br',
    phone: '(11) 98111-2233',
    birthDate: '2016-09-19',
    createdAt: '2024-04-18',
  },
  {
    id: 'pat_05',
    orgId: 'org_mendes_01',
    name: 'Juliana Paes Nogueira',
    cpf: '67142506974',
    email: 'juliana.paes@exemplo.com.br',
    phone: '(11) 98222-3344',
    birthDate: '1986-01-30',
    createdAt: '2024-05-02',
  },
  {
    id: 'pat_06',
    orgId: 'org_mendes_01',
    name: 'Marcelo Castro Silveira',
    cpf: '78253617085',
    email: 'marcelo.castro@exemplo.com.br',
    phone: '(11) 98333-4455',
    birthDate: '1978-08-14',
    createdAt: '2024-05-15',
  },
  {
    id: 'pat_07',
    orgId: 'org_mendes_01',
    name: 'Larissa Montenegro',
    cpf: '89364728196',
    email: 'larissa.m@exemplo.com.br',
    phone: '(11) 98444-5566',
    birthDate: '1992-12-05',
    createdAt: '2024-06-01',
  },
  {
    id: 'pat_08',
    orgId: 'org_mendes_01',
    name: 'Felipe Albuquerque',
    cpf: '90475839207',
    email: 'felipe.albuquerque@exemplo.com.br',
    phone: '(11) 98555-6677',
    birthDate: '1984-06-25',
    createdAt: '2024-06-12',
  },
  {
    id: 'pat_09',
    orgId: 'org_mendes_01',
    name: 'Patrícia Helena Vieira',
    cpf: '11586940318',
    email: 'patricia.vieira@exemplo.com.br',
    phone: '(11) 98666-7788',
    birthDate: '1975-03-17',
    createdAt: '2024-07-03',
  },
  {
    id: 'pat_10',
    orgId: 'org_mendes_01',
    name: 'Gabriel Matos Fonseca',
    cpf: '22697051429',
    email: 'gabriel.matos@exemplo.com.br',
    phone: '(11) 98777-8899',
    birthDate: '2001-10-10',
    createdAt: '2024-07-15',
  },
];

// Helper to get current month YYYY-MM dynamically
const _now = new Date();
const currentYear = _now.getFullYear();
const currentMonth = String(_now.getMonth() + 1).padStart(2, '0');
const curYM = `${currentYear}-${currentMonth}`;

function getOffsetMonthDate(offsetMonths: number, day: number): string {
  const d = new Date(currentYear, Number(currentMonth) - 1 + offsetMonths, day);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${dd}`;
}

export const DEMO_SALES: Sale[] = [
  // 1. CPF: Mariana - À vista, Receita Saúde já emitido
  {
    id: 'sale_01',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_01',
    patientName: 'Mariana Santos Lima',
    patientCpf: '21948375120',
    payerIsBeneficiary: true,
    procedureName: 'Profilaxia e Raspagem Supragengival',
    description: 'Limpeza semestral com remoção de cálculo e profilaxia com jato de bicarbonato',
    totalValue: 350.00,
    serviceDate: `${curYM}-03`,
    paymentMethod: 'PIX',
    installmentsCount: 1,
    installments: [
      {
        id: 'inst_01_1',
        saleId: 'sale_01',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 350.00,
        dueDate: `${curYM}-03`,
        paymentDate: `${curYM}-03`,
        amountReceived: 350.00,
        status: 'RECEBIDO',
        receitaSaudeStatus: 'EMITIDO',
        receitaSaudeId: 'RS-2025-05-0012',
        receitaSaudeEmittedAt: `${curYM}-03T11:20:00Z`,
        paymentMethod: 'PIX',
        bankAccountId: 'bank_01',
      },
    ],
    createdAt: `${curYM}-03T10:00:00Z`,
  },

  // 2. CPF: Rodrigo - Parcelado em 3x. Parcela 1 recebida (Receita Saúde emitido), parcela 2 a receber, parcela 3 a receber
  {
    id: 'sale_02',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_02',
    patientName: 'Rodrigo Alves Ribeiro',
    patientCpf: '34819264035',
    payerIsBeneficiary: true,
    procedureName: 'Tratamento Endodôntico (Canal Molar)',
    description: 'Endodontia do elemento 36 com instrumentação rotatória e obturação termoplastificada',
    totalValue: 1200.00,
    serviceDate: `${curYM}-05`,
    paymentMethod: 'CARTAO_CREDITO',
    installmentsCount: 3,
    installments: [
      {
        id: 'inst_02_1',
        saleId: 'sale_02',
        installmentNumber: 1,
        totalInstallments: 3,
        value: 400.00,
        dueDate: `${curYM}-05`,
        paymentDate: `${curYM}-05`,
        amountReceived: 400.00,
        status: 'RECEBIDO',
        receitaSaudeStatus: 'EMITIDO',
        receitaSaudeId: 'RS-2025-05-0015',
        receitaSaudeEmittedAt: `${curYM}-05T15:30:00Z`,
        paymentMethod: 'CARTAO_CREDITO',
        bankAccountId: 'bank_01',
      },
      {
        id: 'inst_02_2',
        saleId: 'sale_02',
        installmentNumber: 2,
        totalInstallments: 3,
        value: 400.00,
        dueDate: `${curYM}-25`,
        status: 'A_RECEBER',
        receitaSaudeStatus: 'A_EMITIR', // vinculado ao pagamento!
        paymentMethod: 'CARTAO_CREDITO',
      },
      {
        id: 'inst_02_3',
        saleId: 'sale_02',
        installmentNumber: 3,
        totalInstallments: 3,
        value: 400.00,
        dueDate: `2025-06-25`,
        status: 'A_RECEBER',
        receitaSaudeStatus: 'A_EMITIR',
        paymentMethod: 'CARTAO_CREDITO',
      },
    ],
    createdAt: `${curYM}-05T14:00:00Z`,
  },

  // 3. CPF: Lucas (Menor de idade) - Pagador é o Pai (Fernando Rocha)
  {
    id: 'sale_03',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_04',
    patientName: 'Lucas Fernando Rocha (Menor)',
    patientCpf: '56031495863',
    payerIsBeneficiary: false,
    payerName: 'Fernando Pereira Rocha',
    payerCpf: '10987654321',
    procedureName: 'Restauração em Resina Composta',
    description: 'Tratamento odontopediatrico restaurador de 2 dentes decíduos',
    totalValue: 500.00,
    serviceDate: `${curYM}-07`,
    paymentMethod: 'PIX',
    installmentsCount: 1,
    installments: [
      {
        id: 'inst_03_1',
        saleId: 'sale_03',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 500.00,
        dueDate: `${curYM}-07`,
        paymentDate: `${curYM}-07`,
        amountReceived: 500.00,
        status: 'RECEBIDO',
        receitaSaudeStatus: 'EMITIDO',
        receitaSaudeId: 'RS-2025-05-0018',
        receitaSaudeEmittedAt: `${curYM}-07T16:00:00Z`,
        paymentMethod: 'PIX',
        bankAccountId: 'bank_01',
      },
    ],
    createdAt: `${curYM}-07T15:00:00Z`,
  },

  // 4. CPF: Camila - Recebido em dinheiro mas Receita Saúde PENDENTE (Gera alerta no sistema!)
  {
    id: 'sale_04',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_03',
    patientName: 'Camila Beatriz Duarte',
    patientCpf: '45920384752',
    payerIsBeneficiary: true,
    procedureName: 'Clareamento Dental de Consultório',
    description: 'Sessão de clareamento com peróxido de hidrogênio 35%',
    totalValue: 1400.00,
    serviceDate: `${curYM}-08`,
    paymentMethod: 'TRANSFERENCIA',
    installmentsCount: 2,
    installments: [
      {
        id: 'inst_04_1',
        saleId: 'sale_04',
        installmentNumber: 1,
        totalInstallments: 2,
        value: 700.00,
        dueDate: `${curYM}-08`,
        paymentDate: `${curYM}-08`,
        amountReceived: 700.00,
        status: 'RECEBIDO',
        receitaSaudeStatus: 'A_EMITIR', // PENDENTE APÓS RECEBIMENTO!
        paymentMethod: 'TRANSFERENCIA',
        bankAccountId: 'bank_01',
      },
      {
        id: 'inst_04_2',
        saleId: 'sale_04',
        installmentNumber: 2,
        totalInstallments: 2,
        value: 700.00,
        dueDate: `2025-06-08`,
        status: 'A_RECEBER',
        receitaSaudeStatus: 'A_EMITIR',
        paymentMethod: 'TRANSFERENCIA',
      },
    ],
    createdAt: `${curYM}-08T11:00:00Z`,
  },

  // 5. CPF: Vencida e Não Paga (Marcelo Castro)
  {
    id: 'sale_05',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_06',
    patientName: 'Marcelo Castro Silveira',
    patientCpf: '78253617085',
    payerIsBeneficiary: true,
    procedureName: 'Extração de Terceiro Molar Incluso (Siso)',
    description: 'Cirurgia do dente 48 retido com odontossecção e sutura',
    totalValue: 750.00,
    serviceDate: `${curYM}-01`,
    paymentMethod: 'BOLETO',
    installmentsCount: 1,
    installments: [
      {
        id: 'inst_05_1',
        saleId: 'sale_05',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 750.00,
        dueDate: `${curYM}-04`, // Venceu dia 04
        status: 'VENCIDO',
        receitaSaudeStatus: 'A_EMITIR',
        paymentMethod: 'BOLETO',
      },
    ],
    createdAt: `${curYM}-01T09:00:00Z`,
  },

  // 6. CNPJ: Juliana Paes - NFS-e emitida, Implante dentário
  {
    id: 'sale_06',
    orgId: 'org_mendes_01',
    taxOrigin: 'CNPJ',
    patientId: 'pat_05',
    patientName: 'Juliana Paes Nogueira',
    patientCpf: '67142506974',
    payerIsBeneficiary: true,
    procedureName: 'Implante Dentário Cone Morse',
    description: 'Cirurgia de instalação de implante dentário de titânio região 11',
    totalValue: 2800.00,
    serviceDate: `${curYM}-04`,
    paymentMethod: 'CARTAO_CREDITO',
    installmentsCount: 2,
    nfseStatus: 'EMITIDA',
    nfseNumber: '2025/000412',
    nfseVerificationCode: 'A7B8-9F3C-01',
    nfseEmittedAt: `${curYM}-04T17:00:00Z`,
    installments: [
      {
        id: 'inst_06_1',
        saleId: 'sale_06',
        installmentNumber: 1,
        totalInstallments: 2,
        value: 1400.00,
        dueDate: `${curYM}-04`,
        paymentDate: `${curYM}-04`,
        amountReceived: 1400.00,
        status: 'RECEBIDO',
        paymentMethod: 'CARTAO_CREDITO',
        bankAccountId: 'bank_02',
      },
      {
        id: 'inst_06_2',
        saleId: 'sale_06',
        installmentNumber: 2,
        totalInstallments: 2,
        value: 1400.00,
        dueDate: `2025-06-04`,
        status: 'A_RECEBER',
        paymentMethod: 'CARTAO_CREDITO',
      },
    ],
    createdAt: `${curYM}-04T16:00:00Z`,
  },

  // 7. CNPJ: Larissa Montenegro - Alinhador invisível parcelado em 4x, NFS-e a emitir
  {
    id: 'sale_07',
    orgId: 'org_mendes_01',
    taxOrigin: 'CNPJ',
    patientId: 'pat_07',
    patientName: 'Larissa Montenegro',
    patientCpf: '89364728196',
    payerIsBeneficiary: true,
    procedureName: 'Alinhador Invisível - Parcela Tratamento',
    description: 'Etapa inicial de alinhadores transparentes maxila e mandíbula',
    totalValue: 3800.00,
    serviceDate: `${curYM}-10`,
    paymentMethod: 'CARTAO_CREDITO',
    installmentsCount: 4,
    nfseStatus: 'A_EMITIR',
    installments: [
      {
        id: 'inst_07_1',
        saleId: 'sale_07',
        installmentNumber: 1,
        totalInstallments: 4,
        value: 950.00,
        dueDate: `${curYM}-10`,
        paymentDate: `${curYM}-10`,
        amountReceived: 950.00,
        status: 'RECEBIDO',
        paymentMethod: 'CARTAO_CREDITO',
        bankAccountId: 'bank_02',
      },
      {
        id: 'inst_07_2',
        saleId: 'sale_07',
        installmentNumber: 2,
        totalInstallments: 4,
        value: 950.00,
        dueDate: `2025-06-10`,
        status: 'A_RECEBER',
        paymentMethod: 'CARTAO_CREDITO',
      },
      {
        id: 'inst_07_3',
        saleId: 'sale_07',
        installmentNumber: 3,
        totalInstallments: 4,
        value: 950.00,
        dueDate: `2025-07-10`,
        status: 'A_RECEBER',
        paymentMethod: 'CARTAO_CREDITO',
      },
      {
        id: 'inst_07_4',
        saleId: 'sale_07',
        installmentNumber: 4,
        totalInstallments: 4,
        value: 950.00,
        dueDate: `2025-08-10`,
        status: 'A_RECEBER',
        paymentMethod: 'CARTAO_CREDITO',
      },
    ],
    createdAt: `${curYM}-10T14:30:00Z`,
  },

  // 8. CNPJ: Felipe Albuquerque - Prótese Fixa Sobre Implante, NFS-e emitida
  {
    id: 'sale_08',
    orgId: 'org_mendes_01',
    taxOrigin: 'CNPJ',
    patientId: 'pat_08',
    patientName: 'Felipe Albuquerque',
    patientCpf: '90475839207',
    payerIsBeneficiary: true,
    procedureName: 'Prótese Fixa Sobre Implante',
    description: 'Instalação de coroa parafusada sobre implante em zircônia',
    totalValue: 2400.00,
    serviceDate: `${curYM}-11`,
    paymentMethod: 'PIX',
    installmentsCount: 1,
    nfseStatus: 'EMITIDA',
    nfseNumber: '2025/000413',
    nfseVerificationCode: 'D4E2-8A1C-99',
    nfseEmittedAt: `${curYM}-11T16:00:00Z`,
    installments: [
      {
        id: 'inst_08_1',
        saleId: 'sale_08',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 2400.00,
        dueDate: `${curYM}-11`,
        paymentDate: `${curYM}-11`,
        amountReceived: 2400.00,
        status: 'RECEBIDO',
        paymentMethod: 'PIX',
        bankAccountId: 'bank_02',
      },
    ],
    createdAt: `${curYM}-11T15:30:00Z`,
  },

  // 9. CPF: Patrícia Helena - Restauração estética, Receita Saúde emitido
  {
    id: 'sale_09',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_09',
    patientName: 'Patrícia Helena Vieira',
    patientCpf: '11586940318',
    payerIsBeneficiary: true,
    procedureName: 'Restauração em Resina Composta',
    description: 'Restauração estética de dentes anteriores com resina de nanopartículas',
    totalValue: 760.00,
    serviceDate: `${curYM}-12`,
    paymentMethod: 'PIX',
    installmentsCount: 1,
    installments: [
      {
        id: 'inst_09_1',
        saleId: 'sale_09',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 760.00,
        dueDate: `${curYM}-12`,
        paymentDate: `${curYM}-12`,
        amountReceived: 760.00,
        status: 'RECEBIDO',
        receitaSaudeStatus: 'EMITIDO',
        receitaSaudeId: 'RS-2025-05-0021',
        receitaSaudeEmittedAt: `${curYM}-12T18:00:00Z`,
        paymentMethod: 'PIX',
        bankAccountId: 'bank_01',
      },
    ],
    createdAt: `${curYM}-12T17:00:00Z`,
  },

  // 10. CNPJ: Gabriel Matos - Facetas em Resina, Parcela 1 paga, Parcela 2 a receber
  {
    id: 'sale_10',
    orgId: 'org_mendes_01',
    taxOrigin: 'CNPJ',
    patientId: 'pat_10',
    patientName: 'Gabriel Matos Fonseca',
    patientCpf: '22697051429',
    payerIsBeneficiary: true,
    procedureName: 'Facetas de Resina / Cerâmica (Unidade)',
    description: 'Confecção de 4 facetas de resina composta estratificada',
    totalValue: 4800.00,
    serviceDate: `${curYM}-14`,
    paymentMethod: 'CARTAO_CREDITO',
    installmentsCount: 2,
    nfseStatus: 'EMITIDA',
    nfseNumber: '2025/000414',
    nfseVerificationCode: 'B3F7-1C5D-44',
    nfseEmittedAt: `${curYM}-14T19:00:00Z`,
    installments: [
      {
        id: 'inst_10_1',
        saleId: 'sale_10',
        installmentNumber: 1,
        totalInstallments: 2,
        value: 2400.00,
        dueDate: `${curYM}-14`,
        paymentDate: `${curYM}-14`,
        amountReceived: 2400.00,
        status: 'RECEBIDO',
        paymentMethod: 'CARTAO_CREDITO',
        bankAccountId: 'bank_02',
      },
      {
        id: 'inst_10_2',
        saleId: 'sale_10',
        installmentNumber: 2,
        totalInstallments: 2,
        value: 2400.00,
        dueDate: `2025-06-14`,
        status: 'A_RECEBER',
        paymentMethod: 'CARTAO_CREDITO',
      },
    ],
    createdAt: `${curYM}-14T18:00:00Z`,
  },

  // 11. CPF: Rodrigo - Profilaxia preventiva, Recebido via PIX
  {
    id: 'sale_11',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_02',
    patientName: 'Rodrigo Alves Ribeiro',
    patientCpf: '34819264035',
    payerIsBeneficiary: true,
    procedureName: 'Profilaxia e Raspagem Supragengival',
    description: 'Profilaxia preventiva e aplicação tópica de flúor neutro',
    totalValue: 290.00,
    serviceDate: `${curYM}-16`,
    paymentMethod: 'PIX',
    installmentsCount: 1,
    installments: [
      {
        id: 'inst_11_1',
        saleId: 'sale_11',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 290.00,
        dueDate: `${curYM}-16`,
        paymentDate: `${curYM}-16`,
        amountReceived: 290.00,
        status: 'RECEBIDO',
        receitaSaudeStatus: 'EMITIDO',
        receitaSaudeId: 'RS-2025-05-0025',
        receitaSaudeEmittedAt: `${curYM}-16T10:30:00Z`,
        paymentMethod: 'PIX',
        bankAccountId: 'bank_01',
      },
    ],
    createdAt: `${curYM}-16T09:45:00Z`,
  },

  // 12. CPF: Juliana - Clareamento dental, Parcela 1 a receber amanhã
  {
    id: 'sale_12',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_05',
    patientName: 'Juliana Paes Nogueira',
    patientCpf: '67142506974',
    payerIsBeneficiary: true,
    procedureName: 'Clareamento Dental de Consultório',
    description: 'Clareamento combinado moldeira e laser',
    totalValue: 1200.00,
    serviceDate: `${curYM}-18`,
    paymentMethod: 'PIX',
    installmentsCount: 2,
    installments: [
      {
        id: 'inst_12_1',
        saleId: 'sale_12',
        installmentNumber: 1,
        totalInstallments: 2,
        value: 600.00,
        dueDate: `${curYM}-20`,
        status: 'A_RECEBER',
        receitaSaudeStatus: 'A_EMITIR',
        paymentMethod: 'PIX',
      },
      {
        id: 'inst_12_2',
        saleId: 'sale_12',
        installmentNumber: 2,
        totalInstallments: 2,
        value: 600.00,
        dueDate: `2025-06-20`,
        status: 'A_RECEBER',
        receitaSaudeStatus: 'A_EMITIR',
        paymentMethod: 'PIX',
      },
    ],
    createdAt: `${curYM}-18T14:00:00Z`,
  },

  // 13. CNPJ: Mariana Santos - Cirurgia gengival, NFS-e emitida
  {
    id: 'sale_13',
    orgId: 'org_mendes_01',
    taxOrigin: 'CNPJ',
    patientId: 'pat_01',
    patientName: 'Mariana Santos Lima',
    patientCpf: '21948375120',
    payerIsBeneficiary: true,
    procedureName: 'Gengivoplastia e Aumento de Coroa',
    description: 'Cirurgia periodontal estética nos dentes anteriores',
    totalValue: 1600.00,
    serviceDate: `${curYM}-21`,
    paymentMethod: 'CARTAO_DEBITO',
    installmentsCount: 1,
    nfseStatus: 'EMITIDA',
    nfseNumber: '2025/000415',
    nfseVerificationCode: 'C8D1-3E2A-77',
    nfseEmittedAt: `${curYM}-21T16:00:00Z`,
    installments: [
      {
        id: 'inst_13_1',
        saleId: 'sale_13',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 1600.00,
        dueDate: `${curYM}-21`,
        paymentDate: `${curYM}-21`,
        amountReceived: 1600.00,
        status: 'RECEBIDO',
        paymentMethod: 'CARTAO_DEBITO',
        bankAccountId: 'bank_02',
      },
    ],
    createdAt: `${curYM}-21T15:00:00Z`,
  },

  // 14. CPF: Larissa - Restauração simples à vista
  {
    id: 'sale_14',
    orgId: 'org_mendes_01',
    taxOrigin: 'CPF',
    patientId: 'pat_07',
    patientName: 'Larissa Montenegro',
    patientCpf: '89364728196',
    payerIsBeneficiary: true,
    procedureName: 'Restauração em Resina Composta',
    description: 'Restauração classe II molar com matriz seccional',
    totalValue: 380.00,
    serviceDate: `${curYM}-22`,
    paymentMethod: 'PIX',
    installmentsCount: 1,
    installments: [
      {
        id: 'inst_14_1',
        saleId: 'sale_14',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 380.00,
        dueDate: `${curYM}-22`,
        paymentDate: `${curYM}-22`,
        amountReceived: 380.00,
        status: 'RECEBIDO',
        receitaSaudeStatus: 'EMITIDO',
        receitaSaudeId: 'RS-2025-05-0030',
        receitaSaudeEmittedAt: `${curYM}-22T11:00:00Z`,
        paymentMethod: 'PIX',
        bankAccountId: 'bank_01',
      },
    ],
    createdAt: `${curYM}-22T10:15:00Z`,
  },

  // 15. CNPJ: Empresa parceira convênio / Tomador PJ (exemplo Tomador PJ)
  {
    id: 'sale_15',
    orgId: 'org_mendes_01',
    taxOrigin: 'CNPJ',
    patientId: 'pat_08',
    patientName: 'Felipe Albuquerque (Convênio OdontoPrev)',
    patientCpf: '90475839207',
    payerIsBeneficiary: false,
    payerName: 'OdontoPrev S.A.',
    payerCpf: '58119199000187', // CNPJ da operadora
    procedureName: 'Tratamento Endodôntico (Canal Molar)',
    description: 'Glosa liberada e faturamento de procedimentos conveniados',
    totalValue: 980.00,
    serviceDate: `${curYM}-23`,
    paymentMethod: 'TRANSFERENCIA',
    installmentsCount: 1,
    nfseStatus: 'EMITIDA',
    nfseNumber: '2025/000416',
    nfseVerificationCode: 'E9F3-4C1A-22',
    nfseEmittedAt: `${curYM}-23T18:00:00Z`,
    installments: [
      {
        id: 'inst_15_1',
        saleId: 'sale_15',
        installmentNumber: 1,
        totalInstallments: 1,
        value: 980.00,
        dueDate: `${curYM}-28`,
        status: 'A_RECEBER',
        paymentMethod: 'TRANSFERENCIA',
      },
    ],
    createdAt: `${curYM}-23T17:00:00Z`,
  },
];

export const DEMO_EXPENSES: Expense[] = [
  // 1. Salário ASB (Auxiliar em Saúde Bucal) - DEDUTÍVEL PF SIM, FATOR R PJ SIM
  {
    id: 'exp_01',
    orgId: 'org_mendes_01',
    supplierName: 'Ana Paula Ferreira (ASB)',
    supplierCpfCnpj: '32165498700',
    description: 'Salário mensal da auxiliar em saúde bucal da clínica',
    categoryId: 'cat_01_01',
    categoryCode: '01.01',
    categoryName: 'Salários',
    value: 2200.00,
    competenceDate: `${curYM}-05`,
    dueDate: `${curYM}-05`,
    paymentDate: `${curYM}-05`,
    paymentMethod: 'TRANSFERENCIA',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-01T10:00:00Z`,
  },

  // 2. FGTS e Encargos da ASB
  {
    id: 'exp_02',
    orgId: 'org_mendes_01',
    supplierName: 'Caixa Econômica Federal - Guia FGTS',
    supplierCpfCnpj: '00360305000104',
    description: 'Guia do FGTS da funcionária referente ao mês',
    categoryId: 'cat_01_04',
    categoryCode: '01.04',
    categoryName: 'FGTS',
    value: 176.00,
    competenceDate: `${curYM}-07`,
    dueDate: `${curYM}-07`,
    paymentDate: `${curYM}-07`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-01T10:30:00Z`,
  },

  // 3. Aluguel do consultório - PF (Livro Caixa)
  {
    id: 'exp_03',
    orgId: 'org_mendes_01',
    supplierName: 'Imobiliária Jardins Empreendimentos',
    supplierCpfCnpj: '11222333000144',
    description: 'Aluguel do conjunto comercial 42 onde funciona o consultório',
    categoryId: 'cat_02_01',
    categoryCode: '02.01',
    categoryName: 'Aluguel do consultório',
    value: 3800.00,
    competenceDate: `${curYM}-10`,
    dueDate: `${curYM}-10`,
    paymentDate: `${curYM}-10`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-02T09:00:00Z`,
  },

  // 4. Condomínio do edifício comercial - CONDICIONAL PF
  {
    id: 'exp_04',
    orgId: 'org_mendes_01',
    supplierName: 'Condomínio Medical Center Plaza',
    supplierCpfCnpj: '22333444000155',
    description: 'Taxa condominial mensal com água inclusa',
    categoryId: 'cat_02_02',
    categoryCode: '02.02',
    categoryName: 'Condomínio',
    value: 950.00,
    competenceDate: `${curYM}-10`,
    dueDate: `${curYM}-10`,
    paymentDate: `${curYM}-10`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-02T09:15:00Z`,
  },

  // 5. Energia Elétrica da clínica - DEDUTÍVEL PF SIM
  {
    id: 'exp_05',
    orgId: 'org_mendes_01',
    supplierName: 'Enel Distribuição São Paulo',
    supplierCpfCnpj: '61695227000193',
    description: 'Conta de luz da clínica (alta voltagem para compressores e autoclave)',
    categoryId: 'cat_03_01',
    categoryCode: '03.01',
    categoryName: 'Energia elétrica',
    value: 580.00,
    competenceDate: `${curYM}-15`,
    dueDate: `${curYM}-15`,
    paymentDate: `${curYM}-15`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-03T11:00:00Z`,
  },

  // 6. Dental Cremer - Anestésicos e Resinas - DEDUTÍVEL PF SIM
  {
    id: 'exp_06',
    orgId: 'org_mendes_01',
    supplierName: 'Dental Cremer Produtos Odontológicos',
    supplierCpfCnpj: '14190547000108',
    description: 'Caixas de Articaína 4%, resinas Filtek Z350, fitas matriz e adesivo',
    categoryId: 'cat_04_02',
    categoryCode: '04.02',
    categoryName: 'Anestésicos e agulhas',
    value: 1450.00,
    competenceDate: `${curYM}-08`,
    dueDate: `${curYM}-08`,
    paymentDate: `${curYM}-08`,
    paymentMethod: 'CARTAO_CREDITO',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-04T14:00:00Z`,
  },

  // 7. Dental Speed - Materiais de moldagem e descartáveis - DEDUTÍVEL PF SIM
  {
    id: 'exp_07',
    orgId: 'org_mendes_01',
    supplierName: 'Dental Speed Graph',
    supplierCpfCnpj: '08740636000181',
    description: 'Silicone de adição Virtual, alginato Hydrogum, sugadores descartáveis',
    categoryId: 'cat_04_07',
    categoryCode: '04.07',
    categoryName: 'Materiais de moldagem (alginato, silicone)',
    value: 820.00,
    competenceDate: `${curYM}-12`,
    dueDate: `${curYM}-12`,
    paymentDate: `${curYM}-12`,
    paymentMethod: 'PIX',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-06T15:00:00Z`,
  },

  // 8. Luvas e Biossegurança - DEDUTÍVEL PF SIM
  {
    id: 'exp_08',
    orgId: 'org_mendes_01',
    supplierName: 'Medix Brasil Descartáveis',
    supplierCpfCnpj: '03412589000190',
    description: '10 caixas de luvas de nitrilo, máscaras N95, envelopes para esterilização',
    categoryId: 'cat_05_01',
    categoryCode: '05.01',
    categoryName: 'Luvas de procedimento e cirúrgicas',
    value: 650.00,
    competenceDate: `${curYM}-06`,
    dueDate: `${curYM}-06`,
    paymentDate: `${curYM}-06`,
    paymentMethod: 'PIX',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-04T10:00:00Z`,
  },

  // 9. Laboratório de Prótese (TPD) - CONDICIONAL (Coroas de zircônia e placa miorrelaxante)
  {
    id: 'exp_09',
    orgId: 'org_mendes_01',
    supplierName: 'LabPro Dental Laboratório de Prótese',
    supplierCpfCnpj: '29876543000121',
    description: 'Confecção de 2 coroas de zircônia parafusadas e 1 placa de bruxismo',
    categoryId: 'cat_06_01',
    categoryCode: '06.01',
    categoryName: 'Laboratório de prótese (TPD)',
    value: 1250.00,
    competenceDate: `${curYM}-14`,
    dueDate: `${curYM}-14`,
    paymentDate: `${curYM}-14`,
    paymentMethod: 'TRANSFERENCIA',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-08T16:00:00Z`,
  },

  // 10. Coleta de lixo biológico / resíduos - DEDUTÍVEL PF SIM
  {
    id: 'exp_10',
    orgId: 'org_mendes_01',
    supplierName: 'BioEcoponto Resíduos de Saúde',
    supplierCpfCnpj: '05678912000134',
    description: 'Coleta quinzenal e incineração de resíduos infectantes grupo A e perfurocortantes',
    categoryId: 'cat_05_06',
    categoryCode: '05.06',
    categoryName: 'Coleta e descarte de resíduos infectantes',
    value: 290.00,
    competenceDate: `${curYM}-16`,
    dueDate: `${curYM}-16`,
    paymentDate: `${curYM}-16`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-09T11:00:00Z`,
  },

  // 11. Manutenção preventiva de cadeira odontológica e compressor - CONDICIONAL
  {
    id: 'exp_11',
    orgId: 'org_mendes_01',
    supplierName: 'OdontoTech Manutenções Técnicas',
    supplierCpfCnpj: '33444555000166',
    description: 'Troca de mangueiras da cadeira Olsen e filtro coalescente do compressor Stelo',
    categoryId: 'cat_07_01',
    categoryCode: '07.01',
    categoryName: 'Manutenção de cadeira odontológica',
    value: 540.00,
    competenceDate: `${curYM}-17`,
    dueDate: `${curYM}-17`,
    paymentDate: `${curYM}-17`,
    paymentMethod: 'PIX',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-10T12:00:00Z`,
  },

  // 12. Contabilidade mensal - CONDICIONAL
  {
    id: 'exp_12',
    orgId: 'org_mendes_01',
    supplierName: 'Audicont Contabilidade Odontológica',
    supplierCpfCnpj: '44555666000177',
    description: 'Honorários contábeis para fechamento fiscal, DEFIS, folha e Livro Caixa',
    categoryId: 'cat_08_04',
    categoryCode: '08.04',
    categoryName: 'Contabilidade e assessoria fiscal',
    value: 850.00,
    competenceDate: `${curYM}-15`,
    dueDate: `${curYM}-15`,
    paymentDate: `${curYM}-15`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-05T10:00:00Z`,
  },

  // 13. Software Odontológico em Nuvem - CONDICIONAL
  {
    id: 'exp_13',
    orgId: 'org_mendes_01',
    supplierName: 'SimplesDental Softwares',
    supplierCpfCnpj: '15987456000132',
    description: 'Assinatura mensal de prontuário eletrônico e agendamento online',
    categoryId: 'cat_09_01',
    categoryCode: '09.01',
    categoryName: 'Software odontológico e prontuário',
    value: 249.00,
    competenceDate: `${curYM}-10`,
    dueDate: `${curYM}-10`,
    paymentDate: `${curYM}-10`,
    paymentMethod: 'CARTAO_CREDITO',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-02T08:00:00Z`,
  },

  // 14. Anuidade do CRO-SP - DEDUTÍVEL PF SIM
  {
    id: 'exp_14',
    orgId: 'org_mendes_01',
    supplierName: 'Conselho Regional de Odontologia de SP',
    supplierCpfCnpj: '46384111000140',
    description: 'Parcela da anuidade profissional obrigatória do cirurgião-dentista',
    categoryId: 'cat_11_01',
    categoryCode: '11.01',
    categoryName: 'Anuidade do CRO',
    value: 580.00,
    competenceDate: `${curYM}-15`,
    dueDate: `${curYM}-15`,
    paymentDate: `${curYM}-15`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-05T09:00:00Z`,
  },

  // 15. Aquisição de Autoclave nova (Imobilizado) - NÃO DEDUTÍVEL PF
  {
    id: 'exp_15',
    orgId: 'org_mendes_01',
    supplierName: 'Cristófoli Biossegurança',
    supplierCpfCnpj: '80954321000199',
    description: 'Compra de autoclave digital 21L para substituição (Ativo Imobilizado)',
    categoryId: 'cat_14_02',
    categoryCode: '14.02',
    categoryName: 'Autoclave (aquisição)',
    value: 5200.00,
    competenceDate: `${curYM}-03`,
    dueDate: `${curYM}-03`,
    paymentDate: `${curYM}-03`,
    paymentMethod: 'CARTAO_CREDITO',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-01T14:00:00Z`,
  },

  // 16. Combustível do carro próprio do dentista - NÃO DEDUTÍVEL PF
  {
    id: 'exp_16',
    orgId: 'org_mendes_01',
    supplierName: 'Posto Ipiranga Jardim Paulista',
    supplierCpfCnpj: '99888777000111',
    description: 'Abastecimento de gasolina veículo particular do dentista',
    categoryId: 'cat_15_01',
    categoryCode: '15.01',
    categoryName: 'Combustível',
    value: 280.00,
    competenceDate: `${curYM}-11`,
    dueDate: `${curYM}-11`,
    paymentDate: `${curYM}-11`,
    paymentMethod: 'CARTAO_DEBITO',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: false,
    status: 'PAGO',
    createdAt: `${curYM}-11T12:00:00Z`,
  },

  // 17. Despesa Pessoal: Almoço / Restaurante do dentista - NÃO DEDUTÍVEL PF
  {
    id: 'exp_17',
    orgId: 'org_mendes_01',
    supplierName: 'Restaurante Varanda Gourmet',
    supplierCpfCnpj: '77666555000122',
    description: 'Almoço durante horário de intervalo da clínica',
    categoryId: 'cat_16_02',
    categoryCode: '16.02',
    categoryName: 'Alimentação pessoal',
    value: 165.00,
    competenceDate: `${curYM}-13`,
    dueDate: `${curYM}-13`,
    paymentDate: `${curYM}-13`,
    paymentMethod: 'CARTAO_DEBITO',
    bankAccountId: 'bank_01',
    entity: 'CPF',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: false,
    status: 'PAGO',
    createdAt: `${curYM}-13T13:30:00Z`,
  },

  // 18. Tráfego Pago / Anúncios Google Ads - DEDUTÍVEL PF SIM
  {
    id: 'exp_18',
    orgId: 'org_mendes_01',
    supplierName: 'Google Brasil Internet Ltda',
    supplierCpfCnpj: '06990590000123',
    description: 'Campanha de Google Ads busca local para implantes e clareamento',
    categoryId: 'cat_10_01',
    categoryCode: '10.01',
    categoryName: 'Tráfego pago (Google Ads, Meta Ads)',
    value: 800.00,
    competenceDate: `${curYM}-18`,
    dueDate: `${curYM}-18`,
    paymentDate: `${curYM}-18`,
    paymentMethod: 'CARTAO_CREDITO',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'SIM',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'PAGO',
    createdAt: `${curYM}-10T16:00:00Z`,
  },

  // 19. A PAGAR: Pró-labore mensal do Dr. Carlos - FATOR R PJ SIM
  {
    id: 'exp_19',
    orgId: 'org_mendes_01',
    supplierName: 'Dr. Carlos Eduardo Mendes (Sócio)',
    supplierCpfCnpj: '12845678901',
    description: 'Pró-labore mensal do sócio administrador (base Fator R)',
    categoryId: 'cat_01_07',
    categoryCode: '01.07',
    categoryName: 'Pró-labore',
    value: 4500.00,
    competenceDate: `${curYM}-28`,
    dueDate: `${curYM}-28`,
    paymentMethod: 'TRANSFERENCIA',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: true,
    despesaOperacionalPj: true,
    status: 'A_PAGAR',
    createdAt: `${curYM}-01T08:00:00Z`,
  },

  // 20. A PAGAR: Guia DAS do Simples Nacional
  {
    id: 'exp_20',
    orgId: 'org_mendes_01',
    supplierName: 'Receita Federal do Brasil - DAS',
    supplierCpfCnpj: '00394460005887',
    description: 'Guia DAS do Simples Nacional competência mês anterior',
    categoryId: 'cat_13_01',
    categoryCode: '13.01',
    categoryName: 'DAS - Documento de Arrecadação do Simples',
    value: 1380.00,
    competenceDate: `${curYM}-20`,
    dueDate: `${curYM}-20`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'NAO',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'A_PAGAR',
    createdAt: `${curYM}-10T09:00:00Z`,
  },

  // 21. VENCIDO: Taxa de vigilância sanitária municipal
  {
    id: 'exp_21',
    orgId: 'org_mendes_01',
    supplierName: 'Prefeitura Municipal de São Paulo - VISA',
    supplierCpfCnpj: '46392130000103',
    description: 'Taxa anual de fiscalização e alvará sanitário da clínica',
    categoryId: 'cat_02_03',
    categoryCode: '02.03',
    categoryName: 'IPTU e taxas do imóvel',
    value: 480.00,
    competenceDate: `${curYM}-02`,
    dueDate: `${curYM}-04`,
    paymentMethod: 'BOLETO',
    bankAccountId: 'bank_02',
    entity: 'CNPJ',
    dedutivelLivroCaixaPf: 'CONDICIONAL',
    impactaFatorRPj: false,
    despesaOperacionalPj: true,
    status: 'VENCIDO',
    createdAt: `${curYM}-01T11:00:00Z`,
  },
];

// Historical payroll data for Fator R calculation (rolling last 12 months)
export const DEMO_PAYROLL_HISTORY: PayrollHistoryEntry[] = (() => {
  const entries: PayrollHistoryEntry[] = [];
  const now = new Date();
  for (let i = 11; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const isDec = m === '12';
    const salaries = isDec ? 4400 : 2200;
    const charges = isDec ? 1100 : 550;
    const proLabore = 4500;
    entries.push({
      month: `${y}-${m}`,
      salaries,
      charges,
      proLabore,
      totalPayroll: salaries + charges + proLabore,
    });
  }
  return entries;
})();

function getDemoOffsetDate(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
}

export const DEMO_APPOINTMENTS: Appointment[] = [
  // Hoje
  {
    id: 'apt_today_01',
    orgId: 'org_mendes_01',
    patientId: 'pat_01',
    patientName: 'Mariana Santos Lima',
    patientPhone: '(11) 98765-4321',
    patientCpf: '21948375120',
    date: getDemoOffsetDate(0),
    startTime: '08:30',
    durationMinutes: 45,
    endTime: '09:15',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Restauração em Resina Composta (1 Face)',
    procedureId: 'proc_01',
    status: 'FINALIZADA',
    notes: 'Dente 46 oclusal, restauração estética concluída sem sensibilidade.',
    sendWhatsappReminder: true,
    origin: 'WHATSAPP',
    createdAt: '2025-05-01T08:00:00Z',
    updatedAt: '2025-05-01T09:15:00Z',
  },
  {
    id: 'apt_today_02',
    orgId: 'org_mendes_01',
    patientId: 'pat_02',
    patientName: 'Roberto Alves Pereira',
    patientPhone: '(11) 97654-3210',
    patientCpf: '45678912300',
    date: getDemoOffsetDate(0),
    startTime: '10:00',
    durationMinutes: 60,
    endTime: '11:00',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Profilaxia e Raspagem Supragengival',
    procedureId: 'proc_02',
    status: 'EM_ATENDIMENTO',
    notes: 'Profilaxia com ultrassom e aplicação tópica de flúor gel.',
    sendWhatsappReminder: true,
    origin: 'PRESENCIAL',
    createdAt: '2025-05-02T10:00:00Z',
    updatedAt: '2025-05-02T10:00:00Z',
  },
  {
    id: 'apt_today_03',
    orgId: 'org_mendes_01',
    patientId: 'pat_03',
    patientName: 'Camila Souza Dias',
    patientPhone: '(11) 96543-2109',
    patientCpf: '78912345600',
    date: getDemoOffsetDate(0),
    startTime: '14:00',
    durationMinutes: 45,
    endTime: '14:45',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Manutenção Ortodôntica Mensal',
    procedureId: 'proc_03',
    status: 'CONFIRMADA',
    notes: 'Troca de arcos estéticos e ligaduras elásticas.',
    sendWhatsappReminder: true,
    origin: 'WHATSAPP',
    createdAt: '2025-05-03T11:00:00Z',
    updatedAt: '2025-05-03T11:00:00Z',
  },
  {
    id: 'apt_today_04',
    orgId: 'org_mendes_01',
    patientId: 'pat_04',
    patientName: 'Fernando Henrique Castro',
    patientPhone: '(11) 95432-1098',
    patientCpf: '32165498700',
    date: getDemoOffsetDate(0),
    startTime: '15:30',
    durationMinutes: 90,
    endTime: '17:00',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Tratamento Endodôntico Molar',
    procedureId: 'proc_04',
    status: 'CONFIRMADA',
    notes: 'Instrumentação rotatória e medicação intracanal com hidróxido de cálcio.',
    sendWhatsappReminder: true,
    origin: 'TELEFONE',
    createdAt: '2025-05-04T12:00:00Z',
    updatedAt: '2025-05-04T12:00:00Z',
  },
  {
    id: 'apt_today_05',
    orgId: 'org_mendes_01',
    patientId: 'pat_05',
    patientName: 'Larissa Costa Santos',
    patientPhone: '(11) 94321-0987',
    patientCpf: '65498732100',
    date: getDemoOffsetDate(0),
    startTime: '17:15',
    durationMinutes: 30,
    endTime: '17:45',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Avaliação Inicial e Planejamento',
    procedureId: 'proc_06',
    status: 'PENDENTE',
    notes: 'Paciente solicitou encaixe no final da tarde para dor no molar.',
    sendWhatsappReminder: true,
    origin: 'WHATSAPP',
    createdAt: '2025-05-05T14:00:00Z',
    updatedAt: '2025-05-05T14:00:00Z',
  },

  // Amanhã
  {
    id: 'apt_tomorrow_01',
    orgId: 'org_mendes_01',
    patientId: 'pat_06',
    patientName: 'Lucas Mendes Ribeiro',
    patientPhone: '(11) 93210-9876',
    patientCpf: '98732165400',
    date: getDemoOffsetDate(1),
    startTime: '09:00',
    durationMinutes: 60,
    endTime: '10:00',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Clareamento Dental em Consultório',
    procedureId: 'proc_05',
    status: 'CONFIRMADA',
    notes: 'Sessão 2 de 3 de peróxido de hidrogênio 35%.',
    sendWhatsappReminder: true,
    origin: 'WHATSAPP',
    createdAt: '2025-05-06T09:00:00Z',
    updatedAt: '2025-05-06T09:00:00Z',
  },
  {
    id: 'apt_tomorrow_02',
    orgId: 'org_mendes_01',
    patientId: 'pat_07',
    patientName: 'Beatriz Ferreira Lima',
    patientPhone: '(11) 92109-8765',
    patientCpf: '14725836900',
    date: getDemoOffsetDate(1),
    startTime: '10:30',
    durationMinutes: 45,
    endTime: '11:15',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Restauração em Resina Composta (2 Faces)',
    procedureId: 'proc_01',
    status: 'AGUARDANDO',
    notes: 'Aguardando confirmação pelo WhatsApp.',
    sendWhatsappReminder: true,
    origin: 'TELEFONE',
    createdAt: '2025-05-06T10:00:00Z',
    updatedAt: '2025-05-06T10:00:00Z',
  },
  {
    id: 'apt_tomorrow_03',
    orgId: 'org_mendes_01',
    patientId: 'pat_08',
    patientName: 'Gabriel Monteiro Silva',
    patientPhone: '(11) 91098-7654',
    patientCpf: '25836914700',
    date: getDemoOffsetDate(1),
    startTime: '14:00',
    durationMinutes: 60,
    endTime: '15:00',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Exodontia Simples de Dente Erupcionado',
    procedureId: 'proc_07',
    status: 'CONFIRMADA',
    notes: 'Prescrição prévia de amoxicilina e cetoprofeno enviada.',
    sendWhatsappReminder: true,
    origin: 'INDICACAO',
    createdAt: '2025-05-06T11:00:00Z',
    updatedAt: '2025-05-06T11:00:00Z',
  },

  // Ontem
  {
    id: 'apt_yesterday_01',
    orgId: 'org_mendes_01',
    patientId: 'pat_09',
    patientName: 'Juliana Paes de Almeida',
    patientPhone: '(11) 99887-7665',
    patientCpf: '36914725800',
    date: getDemoOffsetDate(-1),
    startTime: '09:00',
    durationMinutes: 60,
    endTime: '10:00',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Profilaxia e Raspagem Supragengival',
    procedureId: 'proc_02',
    status: 'FINALIZADA',
    notes: 'Retorno para manutenção preventiva sem queixas.',
    sendWhatsappReminder: false,
    origin: 'PRESENCIAL',
    createdAt: '2025-05-01T08:00:00Z',
    updatedAt: '2025-05-01T10:00:00Z',
  },
  {
    id: 'apt_yesterday_02',
    orgId: 'org_mendes_01',
    patientId: 'pat_10',
    patientName: 'Rodrigo Silveira Santos',
    patientPhone: '(11) 98776-6554',
    patientCpf: '74185296300',
    date: getDemoOffsetDate(-1),
    startTime: '14:30',
    durationMinutes: 45,
    endTime: '15:15',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Ajuste Oclusal e Placa Miorrelaxante',
    procedureId: 'proc_08',
    status: 'FALTOU',
    notes: 'Paciente não compareceu e não atendeu contato telefônico.',
    sendWhatsappReminder: true,
    origin: 'TELEFONE',
    createdAt: '2025-05-02T12:00:00Z',
    updatedAt: '2025-05-02T15:15:00Z',
  },

  // +2 dias
  {
    id: 'apt_plus2_01',
    orgId: 'org_mendes_01',
    patientId: 'pat_01',
    patientName: 'Mariana Santos Lima',
    patientPhone: '(11) 98765-4321',
    patientCpf: '21948375120',
    date: getDemoOffsetDate(2),
    startTime: '11:00',
    durationMinutes: 30,
    endTime: '11:30',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Polimento e Acabamento de Restauração',
    procedureId: 'proc_01',
    status: 'CONFIRMADA',
    notes: 'Revisão pós-operatória rápida.',
    sendWhatsappReminder: true,
    origin: 'WHATSAPP',
    createdAt: '2025-05-07T08:00:00Z',
    updatedAt: '2025-05-07T08:00:00Z',
  },
  {
    id: 'apt_plus2_02',
    orgId: 'org_mendes_01',
    patientId: 'pat_04',
    patientName: 'Fernando Henrique Castro',
    patientPhone: '(11) 95432-1098',
    patientCpf: '32165498700',
    date: getDemoOffsetDate(2),
    startTime: '15:00',
    durationMinutes: 60,
    endTime: '16:00',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Obturação de Canais Radiculares',
    procedureId: 'proc_04',
    status: 'CONFIRMADA',
    notes: 'Segunda sessão endodôntica para obturação definitiva com guta-percha.',
    sendWhatsappReminder: true,
    origin: 'PRESENCIAL',
    createdAt: '2025-05-07T09:00:00Z',
    updatedAt: '2025-05-07T09:00:00Z',
  },

  // Consultas do mês corrente (competência ativa)
  {
    id: 'apt_fixed_cur_01',
    orgId: 'org_mendes_01',
    patientId: 'pat_01',
    patientName: 'Mariana Santos Lima',
    patientPhone: '(11) 98765-4321',
    patientCpf: '21948375120',
    date: getOffsetMonthDate(0, 5),
    startTime: '09:00',
    durationMinutes: 60,
    endTime: '10:00',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Restauração em Resina Composta (1 Face)',
    procedureId: 'proc_01',
    status: 'FINALIZADA',
    notes: 'Consulta correspondente à receita emitida.',
    sendWhatsappReminder: true,
    origin: 'WHATSAPP',
    saleId: 'sale_01',
    createdAt: `${curYM}-01T09:00:00Z`,
    updatedAt: `${curYM}-05T10:00:00Z`,
  },
  {
    id: 'apt_fixed_cur_02',
    orgId: 'org_mendes_01',
    patientId: 'pat_02',
    patientName: 'Roberto Alves Pereira',
    patientPhone: '(11) 97654-3210',
    patientCpf: '45678912300',
    date: getOffsetMonthDate(0, 10),
    startTime: '10:30',
    durationMinutes: 45,
    endTime: '11:15',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Profilaxia e Raspagem Supragengival',
    procedureId: 'proc_02',
    status: 'FINALIZADA',
    notes: 'Consulta com nota fiscal emitida.',
    sendWhatsappReminder: true,
    origin: 'PRESENCIAL',
    saleId: 'sale_02',
    createdAt: `${curYM}-02T10:00:00Z`,
    updatedAt: `${curYM}-10T11:15:00Z`,
  },
  {
    id: 'apt_fixed_cur_03',
    orgId: 'org_mendes_01',
    patientId: 'pat_03',
    patientName: 'Camila Souza Dias',
    patientPhone: '(11) 96543-2109',
    patientCpf: '78912345600',
    date: getOffsetMonthDate(0, 15),
    startTime: '14:00',
    durationMinutes: 45,
    endTime: '14:45',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Manutenção Ortodôntica Mensal',
    procedureId: 'proc_03',
    status: 'CONFIRMADA',
    notes: 'Consulta de rotina ortodôntica.',
    sendWhatsappReminder: true,
    origin: 'WHATSAPP',
    createdAt: `${curYM}-05T11:00:00Z`,
    updatedAt: `${curYM}-15T14:45:00Z`,
  },
  {
    id: 'apt_fixed_cur_04',
    orgId: 'org_mendes_01',
    patientId: 'pat_04',
    patientName: 'Fernando Henrique Castro',
    patientPhone: '(11) 95432-1098',
    patientCpf: '32165498700',
    date: getOffsetMonthDate(0, 20),
    startTime: '16:00',
    durationMinutes: 90,
    endTime: '17:30',
    dentistName: 'Dr. Carlos Eduardo Mendes',
    procedureName: 'Tratamento Endodôntico Molar',
    procedureId: 'proc_04',
    status: 'CANCELADA',
    notes: 'Desmarcado pelo paciente por motivo de viagem.',
    sendWhatsappReminder: true,
    origin: 'TELEFONE',
    createdAt: `${curYM}-08T14:00:00Z`,
    updatedAt: `${curYM}-19T18:00:00Z`,
  },
];

